### ISSUE TITLE
BaseProcessingPipeline: (buffer full) errors

### ISSUE THREAD

**Issue by Roamer79** [Placeholder-Software/Dissonance#105]
Cannot get Unity and Dissonance to work without constant buffer warning errors.

The Dissonance software still works fine but is seriously choking the network performance and making my multiplayer game unusable. Any ideas? Do I need to change some settings in the network manager?

I am on Unity 2018.1.6.1 and latest Dissonance. 
![20180716_164216](https://user-images.githubusercontent.com/41314882/42795053-87c08cb0-89c5-11e8-8fec-94e16ddb36e0.jpg)

**Comment by martindevans** [comment]
Hi Roamer79

 - Which network integration are you using?
 - Could you run the unity profiler (with deep profiling _off_) and send me the profile results
 - Could you raise debug settings to `Debug` for all categories in `Window > Dissonance > Diagnostic Settings` and send me the log

> seriously choking the network performance

What do you mean by this? These warnings indicate that data is being lost in the microphone capture system, it shouldn't generate any more packets than usual. If you look at the `XXXCommsNetwork` component (exact name depends on which network you're using) what are the numbers like for data rates?

**Comment by martindevans** [comment]
This is possibly related to #106 (same errors shown in the log. But I'm unsure exactly what you mean about choked network performance).

6.2.4 included a fix which _may_ resolve the `lost samples in the preprocessor` problem. That's live on the store now so could you try that out and see if it resolves the issue. If it does _not_ then all the things I asked in my previous post still apply :)

**Comment by martindevans** [comment]
Since this was probably fixed in `6.2.4` I'll close this now. Feel free to re-open the issue if the problem still persists :)

**Comment by gjenningsMT** [comment]
I'm having this issue in the current Dissonance version at the time of typing using Unity 2019.4.29f. I'm not having network issue but when talking either my voice is mangled or silent on the receiving end and vice versa. Same logs in the console about the buffer being full.
