### ISSUE TITLE
[feature] PUN2 Support

### ISSUE THREAD

**Issue by martindevans** [Placeholder-Software/Dissonance#109]
Exit Games are building PUN2 (forum thread [here](https://forum.photonengine.com/discussion/12188/pun-2-early-access-rc1-july-2018?utm_campaign=sendgrid&utm_source=sendgrid.com&utm_medium=email)). Add support for using this as a Dissonance backend.

**Comment by Nesvi** [comment]
How is this going?

**Comment by Nesvi** [comment]
Great!

**Comment by martindevans** [comment]
PUN2 support is now available! It's part of Dissonance 6.2.6 (which I've submitted to the asset store, should go live in a few days). You can download the integration from the [6.2.6 release notes](https://placeholder-software.co.uk/dissonance/releases/6.2.6.html) and use it with Dissonance 6.2.5 :)
