### ISSUE TITLE
Changing scene Exception

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#11]
Hello,

1. We are hosting a scene with one remote client. Dissonance is working correctly.

2. The server call `ServerChangeScene` to initiate a scene change on the host and remote client.

3. In the new scene, the following Exception is thrown and Dissonance doesn't work anymore in the new scene.

![dissonancechangingscene](https://cloud.githubusercontent.com/assets/6678654/20290175/7ef1ab28-ab19-11e6-9dc5-ad8bf2006632.PNG)

The reason seems to be that  `HlapiServer.AddClient` is called before `HlapiCommsNetwork.CreateServer`. Therefore `_network` is null when `AddClient `is called.

Thanks in advance

**Comment by citron4000** [comment]
Just a few precisions: the DissonanceSetup objects are in both scene and none of them are set to DontDestroyOnLoad.

**Comment by citron4000** [comment]
I don't seem to have this problem with 0.0.6 anymore.

**Comment by martindevans** [comment]
Interesting, there were some minor HLAPI fixes included in this release but Tom is still working on the main fix. I guess this will be even more fixed in 0.0.7!
