### ISSUE TITLE
[help/feature] Network quality stats API

### ISSUE THREAD

**Issue by haydenjameslee** [Placeholder-Software/Dissonance#112]
Is it currently possible to get the packet loss percentage and/or any other network quality stats via the Dissonance API? If not we'd appreciate it as an upcoming feature.

Our goal is to show current network conditions to our users, so they are aware when their internet connection is causing sub-optimal voice quality, along with the network quality of other users in the room. Appreciate any suggestions on how to achieve this!

**Comment by martindevans** [comment]
By the way I'll have a look at making those properties public for the next release.

**Comment by martindevans** [comment]
Tom has just merged the PR which exposes this property: `[CanBeNull] public abstract float? PacketLoss { get; }` on the `VoicePlayerState` class. That'll be in the next release :)

**Comment by haydenjameslee** [comment]
Great! We're releasing our voice quality info feature in a week or two and it's coming along well. Just starting to test the threshold values.

**Comment by martindevans** [comment]
[Dissonance 6.2.5](https://placeholder-software.co.uk/dissonance/releases/6.2.5.html) is live on the asset store with the `PacketLoss` property on the `VoicePlayerState` class.
