### ISSUE TITLE
Oculus Audio Spatializer

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#12]
Hello,

We are using the Oculus Rift and the [Oculus Native Spatializer (ONSP)](https://developer3.oculus.com/documentation/audiosdk/latest/concepts/ospnative-unity-overview/).

The ONSP works well on any Audio Source that I have set up in Unity. However, when I do the exact same setup on the Dissonance Playback Audio Source, it doesn't spatialise the voice.

I am just guessing but the problem might come from the Filter function SamplePlaybackComponent that is writing to every channel?

Thanks a lot in advance

**Comment by martindevans** [comment]
I'll look into this one. Unfortunately it could be an extremely complex fix :(

Unity doesn't provide a good way to play procedural audio, so we use the audio filter as a hack to insert the sound into the playback system. I guess it's not too surprising a complex system like the oculus spatializer doesn't like some of the stuff we're doing.

**Comment by citron4000** [comment]
Thanks! Spatialization would add a lot for all VR projects..

Maybe it would be useful to check how they did in the [OVRLipSync ](
https://developer3.oculus.com/downloads/audio/1.0.1-beta/Oculus_OVRLipSync_for_Unity_5/)plugin? They have a way to replay the mic in an Audio Source. Would be interesting to see if their stuff can be spatialized and they did it.

**Comment by citron4000** [comment]
I've tried with the OVRLipSync demo in Unity and it works well with mic and spacialization using their previous OSP system (it's in the OSP folder in Unity when you the OVRLipSync project). So when I attach the `OSP Audio Source` to the `InputType_Sample` object that is replaying the mic input, the sound is spatialized.

But if I try to attach their latest ONSP (`ONSP Audio Source`) to the same object instead of `OSP Audio Source`, then the sound is not spatialized anymore.

I tried to add a `OSP Audio Source` to Dissonance Playback object, and unfortunately it doesn't work either.

**Comment by martindevans** [comment]
I had a brief look into the lip sync demo and unfortunately they're solving a different problem to Dissonance. The Unity microphone system gives you an AudioClip when you start recording, obviously for Dissonance we grab the data out of this and send it across the network wheras for the lip sync they can just play that clip and get local microphone echo. The issue Dissonance has is how to turn some arbitrary data into audio back at the receiving end, Unity has a couple of ways to do this but they're all a little problematic (unreliable, high latency, inefficient). We came up with a system to inject the audio but it happens *after* the spatializer is applied.

I'm looking into injecting the audio further upstream, so the spatializer will affect it.

**Comment by martindevans** [comment]
Just a quick update.

I've found a better way to play back audio which I hope will fix this problem (even if it doesn't, it improves audio playback in a load of other minor ways). I'll push out another test version later today/first thing tomorrow which will include this new playback system.

**Comment by citron4000** [comment]
Awesome, looking forward to the new version!

**Comment by martindevans** [comment]
I've just sent out the new version with this (potential) fix.

**Comment by citron4000** [comment]
Great, it works perfectly now with the last Oculus spatializer! Many thanks for the fix.
