### ISSUE TITLE
Support for Mirror

### ISSUE THREAD

**Issue by fmelogno** [Placeholder-Software/Dissonance#124]
Please, could you add support for Mirror.

Mirror is a high level Networking API for Unity, built on top of the low level Telepathy library.

Mirror is based on Unity's abandoned UNET Networking system.

[https://assetstore.unity.com/packages/tools/network/mirror-129321](https://assetstore.unity.com/packages/tools/network/mirror-129321)

**Comment by martindevans** [comment]
We actually had another feature request for this recently (#120). Unfortunately Telepathy does not support UDP (or any kind of unreliable transport) which makes it unsuitable for voice. There's an optional setting to use a different backend but that affects _all_ of your networking (not just voice) and the author doesn't seem to keen on it. Until that changes we can't support Mirror/Telepathy :(

**Comment by martindevans** [comment]
Actually I should point out that Dissonance not supporting Mirror does not mean you can't use it in your game. Dissonance can use a _different_ backend to your game networking. e.g. you could run your game through Mirror and your voice through [WebRTC Network](https://dissonance.readthedocs.io/en/latest/Basics/Quick-Start-PureP2P/) (hosts it's own p2p voice network for your session).
