### ISSUE TITLE
Opus Access Violation

### ISSUE THREAD

**Issue by AdamKane** [Placeholder-Software/Dissonance#127]
I'm seeing the follow error. Any advice on next steps to diagnose what's up?

`opus.dll caused an Access Violation (0xc0000005) in module opus.dll at 0033:6b7eb79a.`

Here's the stack trace:

Stack Trace of Crashed Thread 6628:

```
0x00007FFC6B7EB79A (opus) opus_encode_float

0x000001D3EB8AF007 (Assembly-CSharp) OpusNativeMethods.opus_encode_float()

0x000001D3EB8ACF4B (Assembly-CSharp) OpusEncoder.EncodeFloats()

0x000001D3EB8AB673 (Assembly-CSharp) Dissonance.Audio.Codecs.Opus.OpusEncoder.Encode()

0x000001D3EB8A99E9 (Assembly-CSharp) Dissonance.Audio.Capture.EncoderPipeline.EncodeFrames()

0x000001D3EB8A8FDB (Assembly-CSharp) Dissonance.Audio.Capture.EncoderPipeline.Handle()
```

**Comment by martindevans** [comment]
That's not something I've seen before. Could you check the integrity of the binaries (Opus.dll) in `Assets/Plugins/Dissonance/Plugins`. Using `Get-FileHash` in powershell you should get:

 - `x86_64/opus.dll` `6D04AC06522189FD0839D45147A0DAA2F6D9F12A70C4D4BBE39647FC29FF068A`
 - `x86/opus.dll` `16F8A48ADD5EBD5D6B6E9D54DDB05AF037F28D95656172C57E4127E065817BA5`

What version of OS/Unity/Dissonance are you using?

**Comment by AdamKane** [comment]
I had been on an out-dated version of Dissonance. Yesterday, we updated to v6.2.5 and happily haven't been able to reproduce any issues. Thanks for the follow-up and I'll check back here if we hit any snags.

**Comment by martindevans** [comment]
Excellent, thanks for checking that.
