### ISSUE TITLE
Persistent Welcome Popup

### ISSUE THREAD

**Issue by AdamKane** [Placeholder-Software/Dissonance#129]
Hello,

On my main PC, the welcome dialog popped up once, I used it and then it stayed quiet.

But on my secodary PC, sync'd via Unity Collaborate, the pop-up keeps, well popping up:
[https://i.imgur.com/I391qn5.png](url)

Any ideas?

Thanks.
![dissonance-popup](https://user-images.githubusercontent.com/276448/47972156-7b3ca900-e03d-11e8-9b63-f5a844b964d3.png)

**Comment by martindevans** [comment]
When the welcome window pops up it _should_ write a file to `Assets/Plugins/Dissonance/Resources/.WelcomeState.json`, this file contains the version of Dissonance the window was last shown for and that is used to ensure that it only automatically pops up once per Dissonance version.

**Is this file not getting created when the window pops up?** If not, try making the file and putting this into it:

    {"_shownForVersion":"6.2.5"}

**Does that stop the window popping up?** If not, try going to `Assets/Plugins/Dissonance/Editor/Windows/Welcome/WelcomeLauncher.cs` and commenting out the line:

    WelcomeWindow.ShowWindow(state);

**Comment by AdamKane** [comment]
![welcome](https://user-images.githubusercontent.com/276448/48294029-fd561480-e425-11e8-846a-8f733ef14868.png)

Thanks. It looks like everything is as it should be in my project (see pic).

I went ahead and commented out the ShowWindow() call.
