### ISSUE TITLE
Voice stops broadcasting on UWP (Hololens)

### ISSUE THREAD

**Issue by FriskyBishop** [Placeholder-Software/Dissonance#132]
I am having an issue with using Dissonance on Hololens

Its working fine on android and PC but on Hololens the voice broadcasting cuts out. 

For example if the speaker talks more than 20 seconds the voice will stop broadcasting.
If the speaker stops speaking and starts again it will broadcast again. 

Dissonance Setup:
Frame Size - medium
Quality - low
Error Correction - On
Noise suppression - High
Mobile Echo Cancellation - Disabled
Desktop Echo Cancellation - Low
Duck Attenuation - 0.75

What could cause this issue? 
Noise suppression? Frame Size?

**Comment by martindevans** [comment]
That sounds like a bug in Dissonance, none of those settings should cause voice to cut out like that!

Are you using the very latest version of Dissonance (6.2.6)? We fixed a similar sounding bug with that release (#121)

**Comment by martindevans** [comment]
Did 6.2.4 fix it?
