### ISSUE TITLE
HlapiCommsNetwork channels always revert back to 0 & 1[bug]

### ISSUE THREAD

**Issue by FriskyBishop** [Placeholder-Software/Dissonance#134]
## Context
Despite setting the channels to 2 & 3 the channels revert back to 0 & 1 on play.

<img src="https://raw.githubusercontent.com/FriskyBishop/VRModels/master/nm.jpg">
Network Settings

<img src="https://raw.githubusercontent.com/FriskyBishop/VRModels/master/dsoff.jpg">
Before hitting 'play'

<img src="https://raw.githubusercontent.com/FriskyBishop/VRModels/master/dson.jpg">
Playing

Dissonance version v6.2.4
Unity 2018.1.6f1

**Comment by martindevans** [comment]
I just went to try and reproduce this and I don't think those channel values are being saved correctly. Doing this:

1. Change channels in Dissonance to 2/3
2. Save scene
3. Load another scene
4. Load the original scene
5. Look at the Hlapi Comms Network

Shows that the channels are still 0/1 at the end, do you see the same?

**Comment by FriskyBishop** [comment]
> I just went to try and reproduce this and I don't think those channel values are being saved correctly. Doing this:
> 
> 1. Change channels in Dissonance to 2/3
> 2. Save scene
> 3. Load another scene
> 4. Load the original scene
> 5. Look at the Hlapi Comms Network
> 
> Shows that the channels are still 0/1 at the end, do you see the same?

if i save scene, load another scene, return to original scene - the values are back to being 0/1

I think it was just Unity being wonky

I solved it by:
1 - removing the Hlapi Comms Network script
2 - saving the scene 
3 - re-adding the Hlapi Comms Network script
4 - setting the channels and 
5 - saving the scene

**Comment by martindevans** [comment]
Thanks for confirming that.

I've improved the HLAPI inspector a bit. It was doing some unusual stuff before which wasn't really necessary, so maybe that was confusing Unity.
