### ISSUE TITLE
[UWP] Audio effect Dissonance Echo Cancellation could not be found

### ISSUE THREAD

**Issue by Alexees** [Placeholder-Software/Dissonance#135]
@martindevans Just want to hook in on this for UWP in Unity 2018.2.6f1. I am receiving this error after upgrading from 6.2.4 to 6.2.6, or I have not noticed it at all since I have implemented it just recently. The size of the copied dll matches the x86 one, so it's the right one and avaiable. They are configured correctly in Unity. I even did a fresh import of the new dissonance package after deleting all the old files.
I can try to revert back to 6.2.4 to see if it was recently introduced, but I doubt it.
Update: same thing with 6.2.4. Trying empty project now
Update: same thing happened again:

New Projekt with 2018.2.6f1, imported dissonance and HLAPI
- added AudioSource to scene referencing mixer with the echo cancelor and disabled audiomixer suspend
- building just that scene and launching it on the hololens shows this error of a missing dll that exists in the project

**Comment by martindevans** [comment]
Is this deploying to the hololens, or just standard desktop UWP?

Could you check the import settings on the files in `Assets/Plugins/Dissonance/Plugins/UWP`, check that the two files (opus/AudioPluginDissonance) in the two folders (x86/x86_64) have import settings corresponding to their location.

<img width="230" alt="untitled" src="https://user-images.githubusercontent.com/177519/49097682-27506900-f265-11e8-907a-67db8796927e.png">

**Comment by Alexees** [comment]
It's Hololens I'm testing this with at the moment.
I double checked. Yes, they are both configured correctly.

**Comment by Alexees** [comment]
This is from the Assets folder:
```
SHA256          326711AFEC8212671056FEB07E874F97DB99FE3BDAC0F313419FEF69B063D245       D:\UnityProjects\MR\CADExplorer\Assets\Plugins\Dissonance\Plugins\UWP\x86\AudioPluginDissonance.dll
SHA256          B7D04E35E36A7E90196A386F8953BE1E6E356B723A2C0673B049E134C3A1E09E       D:\UnityProjects\MR\CADExplorer\Assets\Plugins\Dissonance\Plugins\UWP\x86\opus.dll
SHA256          F63C65A50E264E913F94FD907A646C9980C5BF46F4E33A2A15428F806925DA69       D:\UnityProjects\MR\CADExplorer\Assets\Plugins\Dissonance\Plugins\UWP\x86_64\AudioPluginDissonance.dll
SHA256          B368FC64F3314C415BB26771F3BE1FCC7768ABB0AECB90FFE0061AC6E1C60425       D:\UnityProjects\MR\CADExplorer\Assets\Plugins\Dissonance\Plugins\UWP\x86_64\opus.dll
```

This is from the actual build:
SHA256          F63C65A50E264E913F94FD907A646C9980C5BF46F4E33A2A15428F806925DA69       D:\UnityProjects\MR\CADExplorer\Builds\beta\clientUWP\CAD Explorer (Preview)\Plugins\X64\AudioPluginDissonance.dll
SHA256          326711AFEC8212671056FEB07E874F97DB99FE3BDAC0F313419FEF69B063D245       D:\UnityProjects\MR\CADExplorer\Builds\beta\clientUWP\CAD Explorer (Preview)\Plugins\X86\AudioPluginDissonance.dll
SHA256          326711AFEC8212671056FEB07E874F97DB99FE3BDAC0F313419FEF69B063D245       D:\UnityProjects\MR\CADExplorer\Builds\beta\clientUWP\CAD Explorer (Preview)\AudioPluginDissonance.dll
SHA256          B368FC64F3314C415BB26771F3BE1FCC7768ABB0AECB90FFE0061AC6E1C60425       D:\UnityProjects\MR\CADExplorer\Builds\beta\clientUWP\CAD Explorer (Preview)\Plugins\X64\opus.dll
SHA256          B7D04E35E36A7E90196A386F8953BE1E6E356B723A2C0673B049E134C3A1E09E       D:\UnityProjects\MR\CADExplorer\Builds\beta\clientUWP\CAD Explorer (Preview)\Plugins\X86\opus.dll
SHA256          B7D04E35E36A7E90196A386F8953BE1E6E356B723A2C0673B049E134C3A1E09E       D:\UnityProjects\MR\CADExplorer\Builds\beta\clientUWP\CAD Explorer (Preview)\opus.dll

**Comment by martindevans** [comment]
It looks like something went wrong last time I rebuilt the UWP plugin. The exported symbols from the x86 AudioPluginDissonance are:

    1     0 00019600 Dissonance_ConfigureAecSuppression
    2     1 000194B0 Dissonance_ConfigureNoiseSuppression
    3     2 00018FC0 Dissonance_CreatePreprocessor
    4     3 00019490 Dissonance_DestroyPreprocessor
    5     4 0001A4F0 Dissonance_GetAecMetrics
    6     5 0001A4E0 Dissonance_GetFilterState
    7     6 00019710 Dissonance_GetVadSpeechState
    8     7 000197B0 Dissonance_PreprocessCaptureFrame
    9     8 0001A450 Dissonance_PreprocessorExchangeInstance
    10    9 00018EA0 UnityGetAudioEffectDefinitions

The important one is the final one, that's how queries what audio filters to load from the DLL. The same output for the current UWP/x86/AudioPluginDissonance:

    1    0 00001CF0 Dissonance_ConfigureAecSuppression
    2    1 00001CB0 Dissonance_ConfigureNoiseSuppression
    3    2 000019F0 Dissonance_CreatePreprocessor
    4    3 00001C90 Dissonance_DestroyPreprocessor
    5    4 00001120 Dissonance_GetAecMetrics
    6    5 00001110 Dissonance_GetFilterState
    7    6 00001D70 Dissonance_GetVadSpeechState
    8    7 00001D90 Dissonance_PreprocessCaptureFrame
    9    8 00001080 Dissonance_PreprocessorExchangeInstance

As you can see the `UnityGetAudioEffectDefinitions` function hasn't been exported, which means Unity thinks there are no filters in the DLL. Presumably I misconfigured the linker somehow.

If you email me (martin@placeholder-software.co.uk) your invoice number I'll send you back a fixed DLL as soon as I have one.

**Comment by martindevans** [comment]
I've modified the linker settings to explicitly export the `UnityGetAudioEffectDefinitions` symbol and I've also explicitly named the symbol to prevent C++ name mangling. The exports now look like this:

    1     0 00002820 Dissonance_ConfigureAecSuppression = _Dissonance_ConfigureAecSuppression
    2     1 000027E0 Dissonance_ConfigureNoiseSuppression = _Dissonance_ConfigureNoiseSuppression
    3     2 00002530 Dissonance_CreatePreprocessor = _Dissonance_CreatePreprocessor
    4     3 000027C0 Dissonance_DestroyPreprocessor = _Dissonance_DestroyPreprocessor
    5     4 00001500 Dissonance_GetAecMetrics = _Dissonance_GetAecMetrics
    6     5 000014F0 Dissonance_GetFilterState = _Dissonance_GetFilterState
    7     6 000028A0 Dissonance_GetVadSpeechState = _Dissonance_GetVadSpeechState
    8     7 000028C0 Dissonance_PreprocessCaptureFrame = _Dissonance_PreprocessCaptureFrame
    9     8 00001460 Dissonance_PreprocessorExchangeInstance = _Dissonance_PreprocessorExchangeInstance
    10    9 00001070 UnityGetAudioEffectDefinitions = _UnityGetAudioEffectDefinitions@4

As you can see all the Dissonance symbols are still there, and the `UnityGetAudioEffectDefinitions` symbol has been added without any mangling (i.e. `@4`). I've emailed you this DLL to try out.

**Comment by Alexees** [comment]
@martindevans the problem is gone on the Hololens, thanks for the updated DLL. But it's also missing in the x64 dll which I need for the Mixed Reality Client.

**Comment by martindevans** [comment]
Thanks for checking that and confirming that it's fixed. I'll make the same changes to the 64 bit build now and send you the DLL once it's done :)

**Comment by Alexees** [comment]
Hey Martin,
I looks like all the DLLs are broken. I've now run the project on OculusGO(Android) and the same error appeared.
Could you just run through all of them and push an update or something?

**Comment by martindevans** [comment]
Is the error the same as #110 (Android AEC fails to load)? If so that's a Unity bug and we're waiting for a fix from them.

**Comment by Alexees** [comment]
jup, is. Waiting... :)

**Comment by martindevans** [comment]
Hey Alexees, did you see my [latest post](https://github.com/Placeholder-Software/Dissonance/issues/110#issuecomment-450366709) on the Android issue? According to Unity it's fixed, so hopefully that will fix your Oculus GO problem.
