### ISSUE TITLE
Proximity Chat Failed If Local Player Authority is false

### ISSUE THREAD

**Issue by Dreamer-1911** [Placeholder-Software/Dissonance#140]
## Context
Proximity Chat Failed If Local Player Authority is false

## Expected Behavior
Proximity Chat works properly

## Actual Behavior
When I speak, I can see mic amplitude value change. But can't hear and speaker indication doesn't pop up like in the demo.

## Steps to Reproduce
I mannualy add 5 components to player objects (both local player and remote players) after they are network spawned:
1. Hlapi Player, 2. Voice Broadcast Trigger(Set to Self), 3. A shpere collider trigger, 4. trigger visualizer (I can see the circle after player connects), 5. speaker indication (It doesn't work no matter how close I stand in the circle)

## Your Environment
Unity 2017.4.15
Dissonance Latest Version

**Comment by martindevans** [comment]
I've fixed this 4 days ago and it's ready for the next release. However I forgot to update this issue, I'm *really* sorry about that!

There are two scripts to replace to apply the fix:

Here's the new `Assets/Dissonance/Integrations/UNet_HLAPI/HlapiPlayer.cs` script: https://gist.github.com/martindevans/0676b9c27dd85ba03bb60653354dc43e
Here's the new https://gist.github.com/martindevans/80bc9c434cef5b4a67d5d17a03d2dc16 `Assets/Plugins/Dissonance/Editor/DissonancePlayerEditor.cs` script.

I've tested this and it works in all my tests, tell me if it works for you too :)

**Comment by martindevans** [comment]
Following up on [your forum post](https://forum.unity.com/threads/released-dissonance-unity-voice-chat.438271/page-5#post-4075252) highlighting some problems in the previous fix here's a new HlapiPlayer.cs file which should have those issues fixed: https://gist.github.com/martindevans/b63fbee63c2f7eb1c9c1c81f0a92d33f

**Comment by Dreamer-1911** [comment]
Hi Nyarlathothep,

    1. After investigation, I found why it's not triggered. My players' collision layer set to not to be collided with each other for my gameplay. If I set collision layer to be true, it works. What I can do to make it work and avoid to change gameplay?

    2. When I don't add HlapiPlayer on server. It will trigger and error on clients and I can't enter the game. (It won't happen if I add HlapiPlayer on server)

    IndexOutOfRangeException: NetworkReader:ReadByte out of range:NetBuf sz:45 pos:45
    UnityEngine.Networking.NetBuffer.ReadByte () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkBuffer.cs:35)
    UnityEngine.Networking.NetworkReader.ReadUInt16 () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkReader.cs:179)
    UnityEngine.Networking.NetworkReader.ReadString () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkReader.cs:290)
    Dissonance.Integrations.UNet_HLAPI.HlapiPlayer.OnDeserialize (UnityEngine.Networking.NetworkReader reader, Boolean initialState)
    UnityEngine.Networking.NetworkIdentity.OnUpdateVars (UnityEngine.Networking.NetworkReader reader, Boolean initialState) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:751)
    UnityEngine.Networking.ClientScene.ApplySpawnPayload (UnityEngine.Networking.NetworkIdentity uv, Vector3 position, System.Byte[] payload, NetworkInstanceId netId, UnityEngine.GameObject newGameObject) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/ClientScene.cs:491)
    UnityEngine.Networking.ClientScene.OnObjectSpawn (UnityEngine.Networking.NetworkMessage netMsg) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/ClientScene.cs:552)
    UnityEngine.Networking.NetworkConnection.HandleReader (UnityEngine.Networking.NetworkReader reader, Int32 receivedSize, Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:469)
    UnityEngine.Networking.NetworkConnection.HandleBytes (System.Byte[] buffer, Int32 receivedSize, Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:425)
    UnityEngine.Networking.NetworkConnection.TransportReceive (System.Byte[] bytes, Int32 numBytes, Int32 channelId) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:576)
    UnityEngine.Networking.NetworkClient.Update () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkClient.cs:753)
    UnityEngine.Networking.NetworkClient.UpdateClients () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkClient.cs:965)
    UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:1092)

**Comment by martindevans** [comment]
I replied over on [the forum](https://forum.unity.com/threads/released-dissonance-unity-voice-chat.438271/page-5#post-4097272) again :)

**Comment by martindevans** [comment]
Dissonance [6.3.0](https://placeholder-software.co.uk/dissonance/releases/6.3.0.html) just went live on the asset store, that version includes a fix for this issue. I'll close this issue now, don't hesitate to re-open it if the problem persists :)
