### ISSUE TITLE
Mirror 1.5 and Ignorance 1.2.0

### ISSUE THREAD

**Issue by darrencperry** [Placeholder-Software/Dissonance#144]
## Context
Get Dissonance 6.3.1 working with latest versions of Mirror ([asset store](https://assetstore.unity.com/packages/tools/network/mirror-129321)) and Ignorance ([github release](https://github.com/SoftwareGuy/Ignorance/releases))

## Actual Behaviour
These errors are thrown

`Assets\Dissonance\Integrations\MirrorIgnorance\MirrorIgnoranceClient.cs(54,17): error CS0019: Operator '==' cannot be applied to operands of type 'NetworkMessage' and '<null>'`

`Assets\Dissonance\Integrations\MirrorIgnorance\MirrorIgnoranceCommsNetwork.cs(146,17): error CS0019: Operator '==' cannot be applied to operands of type 'NetworkMessage' and '<null>'`

## Workaround
Comment out `if (netmsg == null)` in both scripts

## Steps to Reproduce
1. Import Mirror 1.5, Ignorance 1.2.0, Dissonance 6.3.1 and the Mirror Ignorance Integration

## Your Environment

- **Unity version**: 2018.3.6f1

- **Editor Operating System and version**: Microsoft Windows 10 Pro

**Comment by martindevans** [comment]
I just updated to the very latest version of Mirror from the asset store and it looks like `NetworkMessage` has been changed from a `class` to a `struct`, hence this error. Removing those checks is the right workaround - they were only there as a sanity check anyway so they should _never_ have returned true.

**Comment by martindevans** [comment]
I've removed those checks and pushed up a new version to the [release notes for 6.3.1](https://placeholder-software.co.uk/dissonance/releases/6.3.1.html).

I also have some other changes that are being tested at the moment (reducing allocations per-packet by working around some of the allocations Mirror makes) which are not included in that package - if you're interested in helping test that shoot me an email (martin@placeholder-software.co.uk).
