### ISSUE TITLE
Unable to select a chatroom in VoiceBroadcastTrigger oor VoiceReceiptTrigger

### ISSUE THREAD

**Issue by Piflik** [Placeholder-Software/Dissonance#145]
## Context
Chat Room dropdown is not drawn if `_roomName` string is empty, both in VoiceBroadcastTrigger and VoiceReceiptTrigger. Obviously this is the default state when one of these scripts is added to a gameObject, making it impossible to use the plugin without editing the scripts.

## Expected Behavior
Display both the room dropdown and the error message stating that no room has been selected

## Actual Behavior
Only the error message is displayed

## Workaround
Edit the scripts to have a valid `_roomName` string and Reset the monobehaviours on the gameobject, or add new ones.

## Fix
Edit the Custom inspectors so both UI elements are displayed.
Add 
`EditorGUILayout.EndHorizontal();`
`EditorGUILayout.BeginHorizontal();`

into the `if (string.IsNullOrEmpty(transmitter.RoomName))...` part in order to display the dropdown on a new line.

## Steps to Reproduce
1. Add a VoiceBroadcastTrigger or VoiceReceiptTrigger to a gameobject

- **Dissonance version used**: v6.3.1 

- **Unity version**: 2018.3.8f1

**Comment by martindevans** [comment]
Thanks for reporting this. I don't quite see the same problem, as you can see in this gif it is displaying the dropdown UI but it's horribly aligned and quite possibly off the side of your screen:

![2019-03-14_16-36-31](https://user-images.githubusercontent.com/177519/54374655-7b962200-4677-11e9-9469-fba335b3b08c.gif)

This is obviously a horrible UI, I'll fix it right away!

**Comment by Piflik** [comment]
Yeah, I found it after posting the issue. I used EndHoroizontal and BeginHorizontal to place it below the "No Room" label. Alternative, this label could be removed entirely since it doesn't add any information that the Error Message doesn't already display more pprominently.

**Comment by martindevans** [comment]
Yeah I'm not quite sure why that label exists. The git blame log says it was added to handle an edge case around rooms being deleted (leaving triggers that reference that room in a weird state), but it's obviously not working as expected!

**Comment by martindevans** [comment]
This was released in Dissonance 6.4.0 (2 weeks ago, but I forgot to update this issue)
