### ISSUE TITLE
[bug] Memory Free Error on iOS

### ISSUE THREAD

**Issue by yohawing** [Placeholder-Software/Dissonance#155]
## Context

App crash when I start voice connection.
It seem to be see error on `Assets/Plugins/Dissonance/Plugins/iOS/libAudioPluginDissonance.a`.

```
[Dissonance:Recording] (08:54:36.153) BasicMicrophoneCapture: Began mic capture (SampleRate:48000Hz, FrameSize:960, Buffer Limit:2^13, Latency:20ms, Device:'')
Dissonance.Logs:SendLogMessage(String, LogLevel)
Dissonance.Log:WriteLog(LogLevel, String)
Dissonance.Log:WriteLogFormat(LogLevel, String, TA, TB, TC, TD, TE)
Dissonance.Audio.Capture.BasicMicrophoneCapture:StartCapture(String)
Dissonance.Audio.Capture.CapturePipelineManager:RestartTransmissionPipeline(String)
Dissonance.Audio.Capture.CapturePipelineManager:Update(Boolean, Single)
Dissonance.DissonanceComms:Update()
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Export/Debug.bindings.h Line: 43)

testapp(5847,0x1716af000) malloc: Incorrect checksum for freed object 0x116873608: probably modified after being freed.
Corrupt value: 0x42c8000042c80000
testapp(5847,0x1716af000) malloc: *** set a breakpoint in malloc_error_break to debug

```

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: e.g. v6.4.0

- **Unity version**: e.g. 2018.2.5f1 Personal

- **Editor Operating System and version**: MacOS 10.14.15

- **Build Settings**: iOS 12.3.1 
XCode10.2.1 Deployment target 11.0

**Comment by martindevans** [comment]
Hi yohawing,

Someone else recently reported a similar issue and it turned out to be because there were two incompatible versions of the same plugin installed. Do you have any other plugins installed which may include opus or webrtc libraries? e.g. Photon voice.
