### ISSUE TITLE
 [help] Dlls Not Found Error Android, AudioPluginDissonance and Opus

### ISSUE THREAD

**Issue by mirzasohailbaig** [Placeholder-Software/Dissonance#159]
I recently had to make changes to the Unity build configuration to upload a Android 64-bit version of our app to store. The app works fine but I get DLL not found error for AudioPluginDissonance and Opus. I've added images of my configuration and the errors I'm getting. Any help on this would be much appreciated .

## My Environment
- **Dissonance version used**: e.g. v6.4.1

- **Unity version**: e.g. 2018.4.6f1 Personal 

- **Editor Operating System and version**: e.g. Microsoft Windows 10 Pro (x64) 
##
- **Build Settings**: Android (image below)
![Configuration](https://user-images.githubusercontent.com/8581543/63981022-01b9ef80-ca83-11e9-9d16-f0f74af69c07.png)

##

![AudioPluginDissonance_Not_Found](https://user-images.githubusercontent.com/8581543/63980683-eb5f6400-ca81-11e9-8570-c4f421df4f7a.jpg)

##
![opus_Dll_Not_Found](https://user-images.githubusercontent.com/8581543/63980684-eb5f6400-ca81-11e9-920d-62a4fefdee8d.jpg)

**Comment by martindevans** [comment]
Did you resolve this issue?

**Comment by mirzasohailbaig** [comment]
No I posted it on reddit instead.
