### ISSUE TITLE
Use assembly definitions

### ISSUE THREAD

**Issue by lemcheyWhite** [Placeholder-Software/Dissonance#161]
Hi, It would be nice to have assembly definitions (https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) for the main project (Dissonance) and for integration as well. Do you have any plans to implement it?

Thank you!

**Comment by lemcheyWhite** [comment]
Found related issue #101, but I can't see asmdef in package preview\import window.

**Comment by martindevans** [comment]
Dissonance doesn't ship with asmdefs at the moment as not everyone uses them in their project and they're a bit inconvenient in that case. Instead we've made sure that it's relatively easy to add asmdefs to Dissonance if you need them - check out the instructions on how to add asmdefs [here](https://dissonance.readthedocs.io/en/latest/Tutorials/Assembly-Definitions/).

**Comment by martindevans** [comment]
I should mention that #101 (when we made this decision) was almost a year ago. We'll probably add asmdefs to the package in the near future, as more and more people are using them.

**Comment by lemcheyWhite** [comment]
I've tried to use the instruction but looks like it doesn't work anymore as excepted
For example:
NotNullAttribute class is internal in Dissonance\Core\Jetbrains, but it's used in Dissonance\Editor classes and when I add assembly definitions, class NotNullAttribute is not accessible anymore from Editor assembly. 

It's only one example, as a workaround I can change accessor modified to public in this case, but it requires a lot of work after upgrade to a new version.

**Comment by martindevans** [comment]
I'll investigate this soon and (hopefully) it'll all be fixed up by the next release :)

**Comment by martindevans** [comment]
With Dissonance [6.4.3](https://placeholder-software.co.uk/dissonance/releases/6.4.3.html) we've added assembly definitions to Dissonance.
