### ISSUE TITLE
[help] Unable To Distribute to Apple Mac Store due to i386 slice presence

### ISSUE THREAD

**Issue by davegreco** [Placeholder-Software/Dissonance#168]
## Context
I'm unable to upload a build through iTunes connect, it rejects the binary due to the fact that the opus package that is built for Mac contains a i386 slice of code, it only allows 64bit.

## Expected Behavior
the ability to submit what I have built to the app store

## Actual Behavior
app gets rejected due to the maintained binary from dissonance

## Workaround
no work around found except to disable voice and remove the binary from my project, not really a work around just an annoying step and a degraded experience in my app.

## Fix
It seems like the opus package just needs to be re-built with Xcode tools or whatever to not include an i386 slice. Maybe there is a work around, but I messed around with target settings and it just seems like there is no way to avoid including that i386 slice with the Mac library that is built.

## Steps to Reproduce
1. build an app for the Mac standalone platform with this plugin in it
2. attempt to submit to apple through iTunes connect
3.
4.

## Your Environment

latest version of dissonance

latest version for unity 2019

- OSX Catalina, but same result on another machine that isn't upgraded

- **Build Settings**: Mac

- **Link to your project**: I can't provide this, I could provide snippets but this isn't an issue with my code.

**Comment by martindevans** [comment]
Just to double check, are you using the binaries in `Assets\Plugins\Dissonance\Plugins\macOS`? These are "fat" binaries which include the x86 and the x64 architectures in one file. We used to have separate x86 and x64 binaries and actually upgraded to a fat binary a while ago. Those old files are still in `Assets\Plugins\Dissonance\Plugins\x86_64`, you _may_ be able to enable the import settings for those and disable them for the other bundle files. However, I expect they're very out of date now so that would resolve your store submission problem, but break Dissonance!

Could you send me an email (martin@placeholder-software.co.uk) with your invoice number and I'll get back to you with the replacement binaries ASAP.

**Comment by martindevans** [comment]
I've just rechecked the build process, we've removed fat binary support for the preprocessor (`AudioPluginDissonance.bundle`) and only still have it for opus. In this case you can probably use the older `opus.bundle` in `Assets\Plugins\Dissonance\Plugins\x86_64` to resolve your issue right away. It's slightly out of date, but it should still be compatible.

**Comment by davegreco** [comment]
Thank you for the super quick reply. That is correct, it is only for the opus bundle that the fat binary seems to exist. I'll try deleting the one bundle and setting that opus bundle as part of the target to get me by for now. I didn't know that I could use that file for Mac, but it makes sense that it is the same.

Am I good to leave this open as a reminder until the other bundle is updated/removed?

Thanks again!!!

**Comment by martindevans** [comment]
Would you mind still sending me that email, I'll have some newer opus bundles built next week and it'd be helpful to confirm that they work for you before we push that to the store.

Leave this issue open for now, I'll close it once we have a fix pushed up to the asset store version :)

**Comment by davegreco** [comment]
Thanks, I just sent that over.

**Comment by davegreco** [comment]
Love the plugin BTW!

I'm curious if you have any tips or options on running this in it's own network. We've been considering switching to photon voice, not because we don't like this but with 10-12 people it's killing our message limit on photon, using theirs it's ran through a separate network and doesn't count towards the limit. Totally not a problem with your product but curious on any ideas to continue using it long term. Right now it hasn't become an issue but we know (from experience) if a lot more people start using it our message consumption will become an issue.

**Comment by martindevans** [comment]
An immediate change you can make is to increase the the "frame size" [docs](https://dissonance.readthedocs.io/en/latest/Reference/Audio/VoiceSettings/index.html#frame-size) to the maximum, this will pack more audio into a single packet (at the cost of increasing latency of course). That'll send about 2/3rds as many messages as the default setting.

Ultimately if you want to migrate off Photon networking for the voice that should actually be relatively easy - Dissonance supports a lot of network backends out of the box (11) or you can build a custom network backend. You could run your "game networking" through photon and then use a different backend just for voice (e.g. [webrtc networking](https://assetstore.unity.com/packages/slug/143294?aid=1100lJDF) for completely P2P voice). We actually _just_ launched a [Discord server](https://placeholder-software.co.uk/discord) for Placeholder Software today, feel free to join up there if you want to discuss this kind of stuff some more :)

**Comment by davegreco** [comment]
Wonderful, thank you! I’ll join there soon. I appreciate the ideas.
