### ISSUE TITLE
selecting a prefab with DissonanceComms lets cursor flicker

### ISSUE THREAD

**Issue by Alexees** [Placeholder-Software/Dissonance#169]
## Context
When I select a prefab with DissonanceComms on it (DissonanceSetup) in the Editor the Windows cursor starts to flicker between cursor and loading indicator.

I'm suspecting it's the DissonanceCommsEditor which calls `EditorUtility.SetDirty(comms)` at the end of `OnInspectorGUI()` no matter what.
commenting it out stops the behaviour but is no solution.

## Expected Behavior
no cursor flicker

## Actual Behavior
cursor flicker

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. Create and select a prefab with the DissonanceComms component on it

## Your Environment

- **Dissonance version used**: v6.4.3

- **Unity version**: 2018.4.12f1

- **Editor Operating System and version**: Microsoft Windows 10 Pro 10.0.18362 (x64)

- **Build Settings**: Android

**Comment by Alexees** [comment]
It's the same with the VoiceBroadcastTrigger. It's basically every script that calls EditorUtility.SetDirty unfiltered

**Comment by martindevans** [comment]
Thanks for reporting this, I'll look into this now.

**Comment by martindevans** [comment]
> I was wondering why that call is even made?

Now that I've looked into it I see why that call is made unconditionally in some places.

Some of our editors show live information, e.g. at runtime `DissonanceComms` shows a list of users along with indicators of if they are speaking - the `SetDirty` call is a hacky way to make the editor constantly redraw to keep this finromation fresh.

Using `public override bool RequiresConstantRepaint() => true` is a much better way to do this!

**Comment by martindevans** [comment]
Oops, that was autoclosed when the PR was merged. I'll leave it open until it's released on the asset store.

**Comment by martindevans** [comment]
Dissonance 6.4.4 just went live, that should fix this.
