### ISSUE TITLE
Changing AudioMixer during a session

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#17]
Hello,

We are using the last version of Unity and using AudioMixer. When it is set in the AudioSource of the Playback prefab, it works perfectly. However, when we try to change it programmaticaly, the sound cuts off and doesn't come back. Here is what we use to change the AudioMixer.

> AudioMixer mixer = Resources.Load("Mixer_name") as AudioMixer;
> 
> string _OutputMixer = mixerName;
> player.GetComponent<AudioSource>().outputAudioMixerGroup = mixer.FindMatchingGroups(_OutputMixer)[0];

Note that drag and drop within the editor produce the same result.

It would be extremely useful to be able to change the AudioMixer of the Playback depending on the state of a player.

Thanks in advance for your help!

**Comment by martindevans** [comment]
Hi Citron,

I've just tried this in the Unity editor (simply dragging and dropping a mixer) and that *does* continue working as expected so unfortunately I can't reproduce this. A few follow up questions:

 - What exact version of Unity are you on?
 - If you create an AudioSource yourself and change the mixer like this does it work?
 - Does AudioSource.isPlaying still return true after you have changed the mixer and playback is broken?
 - There are a few critical settings which cannot be changed, are these all at the following values after the mixer has changed:

```
audioSource.loop = true;
audioSource.pitch = 1;
audioSource.clip = null;
audioSource.playOnAwake = false;
```

Unfortunately I'm drawing a bit of a blank on what else could cause this!

**Comment by citron4000** [comment]
Hi Martin,

Thanks for your reply!

After more testing, drag & drop as well as the code above both work. The problem was caused by one of the AudioMixer having a different `Pitch` than 100%. I think you can reproduce the problem by trying to change it directly in the editor. The sounds will stop working.

The work-around that we are using is to add a `Pitch Shifer` instead. It seems to accomplish the same thing than pitch and works with Dissonance.

Thanks again!

**Comment by martindevans** [comment]
Glad you fixed it :)

It's actually an interesting point that Dissonance does not work with an AudioMixer pitch set to something else I'll have to investigate that!
