### ISSUE TITLE
Documentation mentions deprecated WebRTC

### ISSUE THREAD

**Issue by Alexees** [Placeholder-Software/Dissonance#171]
The following page mentions WebRTC and provides a link, but that asset is gone:
https://dissonance.readthedocs.io/en/latest/Basics/Choosing-A-Network/index.html#network-integrations

**Comment by martindevans** [comment]
Thanks for pointing this out.

They used to provide a free package which has since been deprecated, now it requires using their [paid package](https://assetstore.unity.com/packages/tools/network/webrtc-video-chat-68030?aid=1100lJDF). I've pushed up a fix for this.
