### ISSUE TITLE
Starting server logs "Constructing Host"

### ISSUE THREAD

**Issue by Alexees** [Placeholder-Software/Dissonance#173]
I don't know if this is on purpose, but I find it confusing.
I have a Unity project running in client/server mode (no Host).
I'm not even constructing any VoiceBroadcast-/ VoiceReceiptTrigger on the server and still, the BaseServer class logs in its constructor:
`Log.Info("Constructing host. SessionId:{0}", _sessionId);`

Does this mean the server is participating as a Host no matter the way the NetworkManager was startet?
Maybe it's a different kind of host, but that should be made more clear.

Just a suggestion

**Comment by martindevans** [comment]
That message is badly worded, I'll go and change it now. Thanks for pointing this out.

The BaseServer is started in both `Host` mode (which runs client and server) and `Dedicated Server` mode (which just starts the server). This message just indicates that the `BaseServer` has been constructed.

**Comment by martindevans** [comment]
Autoclosed by PR merge again, sorry about that. I'll leave it open until it's on the store.

**Comment by martindevans** [comment]
Dissonance 6.4.4 just went live. That changes the message from `Constructing host. SessionId:{0}` to `Created server with SessionId:xxx`
