### ISSUE TITLE
UWP Plugins configured wrong causing build error

### ISSUE THREAD

**Issue by Alexees** [Placeholder-Software/Dissonance#174]
The AudioPluginDissonance.dll's and Opus.dlls cause an issue when building for UWP throwing this error:

`Plugin <Plugin> must have identical settings for all SDKs`

Even though the dlls for ARM might only be used on UWP, either all 3 apperances (x32, x64, ARM) need to be set to UWP, or all to Any SDK. A mix is not allowed.

**Comment by martindevans** [comment]
Is it showing the `Platform Settings > Scripting backend` _not_ set to `Any Scripting Backend` for you? If so, which version of Unity are you using?

I see them as all set to `Any Scripting Backend` on my local copy (2017.4), if you're not using that then I guess this is some kind of import/export problem associated with how we build the package for distribution through the asset store.

**Comment by Alexees** [comment]
Yes, for ARM they were set to UWP only.
I'm using 2018.4.12f1.
I checked that in two of my project and one if them is a fresh import from the store.

**Comment by martindevans** [comment]
Thanks for checking that. I'll have to double check that these settings have exported properly next time we do an update (in a week or two most likely).

**Comment by martindevans** [comment]
Dissonance 6.4.4 just went live, that should fix this for all Unity versions.
