### ISSUE TITLE
NullReferenceException In DissonanceComms Inspector

### ISSUE THREAD

**Issue by martindevans** [Placeholder-Software/Dissonance#180]
Reported [on Discord](https://discordapp.com/channels/631607020310495232/631607497760702483/686822768502898688) by Austin:

> hello, i updated to v6.4.5 from the Asset Store and am now getting this error when i have the DissonanceSetup prefab selected (using TNet integration and Unity 2019.3.4f1):

```NullReferenceException: Object reference not set to an instance of an object
Dissonance.Editor.DissonanceCommsEditor.PlaybackPrefabGui (Dissonance.DissonanceComms comm) (at Assets/Plugins/Dissonance/Editor/DissonanceCommsEditor.cs:105)
Dissonance.Editor.DissonanceCommsEditor.OnInspectorGUI () (at Assets/Plugins/Dissonance/Editor/DissonanceCommsEditor.cs:53)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass55_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <d0ffe769b7a34b4cac3a7cdc5c696293>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
it's pointing to line 105 in DissonanceCommsEditor.cs: if (!string.IsNullOrEmpty(_lastPrefabError.stringValue))
```

Workaround: Add `[SerializeField]` onto the `_lastPrefabError` field in `DissonanceComms`.

**Comment by martindevans** [comment]
An update that fixes this has been submitted to the asset store (6.4.6), it should be live in a few days.

**Comment by martindevans** [comment]
Dissonance 6.4.6 is now live with a fix for this issue.

**Comment by nrgapple** [comment]
What is the work around for this error? Is `6.4.5` just broke?
