### ISSUE TITLE
Oculus Quest Permission Dialog

### ISSUE THREAD

**Issue by martindevans** [Placeholder-Software/Dissonance#181]
On the Oculus Quest the permissions dialog for microphone access never appears, this breaks voice since Dissonance cannot read any data from the mic.

It has been reported that the fix for this is to add this line to the `AndroidManifest.OVRSubmission` file:

    <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="false" />

**Comment by ScottMichaud** [comment]
One solution that worked for me was having my build index 0 scene be an all-black void. The actual starting scene of the game is build index 1. A GameObject in this scene has the following MonoBehaviour. (You can also add other boot workloads to this script.) I had valid permissions by the time build index 1 was loaded.

```
using UnityEngine;
using UnityEngine.Android;
using UnityEngine.SceneManagement;

// Some class that derives from MonoBehaviour
void Start()
{
    #if PLATFORM_ANDROID
    if (Permission.HasUserAuthorizedPermission(Permission.Microphone) == false)
    {
        Permission.RequestUserPermission(Permission.Microphone);
    }
    #endif
    
    SceneManager.LoadSceneAsync(1, LoadSceneMode.Single);
}
// Rest of class.
```
