### ISSUE TITLE
[Feature] Offline Recording Mode

### ISSUE THREAD

**Issue by martindevans** [Placeholder-Software/Dissonance#182]
Some people have requested a way to use Dissonance even when offline, just as a local voice recorder (with better audio quality thanks to AEC/NS/AGC preprocessing).

Implementation note: Consider implementing this as a network session that pretends it's online but isn't actually. This should trick Dissonance into running the entire capture pipeline as normal.

**Comment by Gustorvo** [comment]
Could you please explain a little bit more in details here? How exactly do I "fool" the system and pretend it's online when it isn't by fact?

**Comment by martindevans** [comment]
When Dissonance starts up it finds a behaviour implementing `ICommsNetwork` (Assets/Plugins/Dissonance/Core/Networking/ICommsNetwork.cs), this behaviour encapsulates all the interactions with the network and Dissonance runs in the way it demands - when the network is offline, Dissonance does nothing.

To get voice flowing you need a few things:
 - You must be online (network behaviour `Status=Connected`).
 - The network mode must require voice (network behaviour `Mode=Client/Host`).
 - Someone must be listening (PlayerJoined event).
 - You must be speaking (open a channel to the fake player).

Once this is setup Dissonance will be recording audio and sending it to the network system (which can then throw the packets away). You can get access to this stream of raw audio with `DissonanceComms.SubscribeToRecordedAudio`.

**Comment by martindevans** [comment]
[Dissonance 8.2.0](https://placeholder-software.co.uk/dissonance/releases/8.2.0.html) is now live on the [asset store](https://assetstore.unity.com/packages/tools/audio/dissonance-voice-chat-70078?aid=1100lJDF) with the new `OfflineCommsNetwork` included in the main package.

**Comment by jackyetz** [comment]
> 

Hi martin,

Could u provide a step-by-step instruction using "Offline Comms Network" as this instruction in https://placeholder-software.co.uk/dissonance/docs/Tutorials/Acoustic-Echo-Cancellation.html
