### ISSUE TITLE
Server build no connection

### ISSUE THREAD

**Issue by Twcd** [Placeholder-Software/Dissonance#183]
The voice chat is not working when we make a server build but work on "normal server".

Unity version : 2019.2.18f1
Dissonance 6.4.1

Log : 
Mono path[0] = 'C:/Users/Ga├½l/Desktop/build/XXX/Managed'
Mono config path = 'C:/Users/Ga├½l/Desktop/build/MonoBleedingEdge/etc'
Initialize engine version: 2019.2.18f1 (bbf64de26e34)
[XR] Discovering subsystems at path C:/Users/Ga├½l/Desktop/build/XXX/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.133 seconds

UnloadTime: 0.505900 ms
Starting console
Server Tick Rate set to: 30 Hz.
Server: Start port=7777
Server has started
Server: listening port=7777
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
TelepathyTransport initialized!

ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'HDRP/Unlit' - Setting to default shader.
UnloadTime: 6.914000 ms
HDR Render Texture not supported, disabling HDR on reflection probe.

(Filename: C:\buildslave\unity\build\Runtime/Camera/ReflectionProbes.cpp Line: 276)

HDR Render Texture not supported, disabling HDR on reflection probe.

(Filename: C:\buildslave\unity\build\Runtime/Camera/ReflectionProbes.cpp Line: 276)

Unloading 13 unused Assets to reduce memory usage. Loaded Objects now: 6003.
Total: 1.378100 ms (FindLiveObjects: 0.420200 ms CreateObjectMapping: 0.041900 ms MarkObjects: 0.652600 ms  DeleteObjects: 0.262900 ms)

Dedicated server mode : True
Finished loading scene in host mode.
StartHostClient called
New player connected. IP : localhost
New player connected. IP : ::1
Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Received request data from : 2222
Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unknown message ID 8290 connection(1)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by Twcd** [comment]
This what i see on the client : 
Dedicated server mode : False
test
[Dissonance:Recording] (23:11:49.344) VoiceSettings: Loaded Pref Dissonance_Audio_Quality = High
[Dissonance:Recording] (23:11:49.353) VoiceSettings: Loaded Pref Dissonance_Audio_FrameSize = Medium
[Dissonance:Core] (23:11:49.355) DissonanceComms: Loading default playback prefab
DEBUG [Dissonance:Recording] (23:11:49.388) CapturePipelineManager: Not changing microphone device from '' to '' (equivalent devices)
[Dissonance:Core] (23:11:49.394) DissonanceComms: Starting Dissonance Voice Comms (6.4.1)
- Network: [DissonanceSetup(Clone) (Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceCommsNetwork)]
- Quality Settings: [Quality: High, FrameSize: Medium, FEC: True, DenoiseAmount: High, VoiceDuckLevel: 0,75]
- Codec: [Codec: Opus, FrameSize: 1920, SampleRate: 48kHz]
DEBUG [Dissonance:Core] (23:11:49.420) VoiceReceiptTrigger: Recalculating token activation: 0 tokens, activated: True
DEBUG [Dissonance:Core] (23:11:49.424) Rooms: Joined chat room 'Global'
gi::BakeBackendSwitch: Clear() active clients.
gi::BakeBackendSwitch: switching bake backend from 3 to 1.
Unloading 374 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 2.803600 ms
Loaded scene 'Assets/Scenes/SampleScene.unity'
	Deserialize:            201.453 ms
	Integration:            240.251 ms
	Integration of assets:  12.979 ms
	Thread Wait Time:       60.888 ms
	Total Operation Time:   515.571 ms
Finished loading scene in client-only mode.
System memory in use before: 440.4 MB.
System memory in use after: 438.7 MB.

Unloading 4453 unused Assets to reduce memory usage. Loaded Objects now: 8825.
Total: 12.200700 ms (FindLiveObjects: 1.039600 ms CreateObjectMapping: 0.253700 ms MarkObjects: 9.369300 ms  DeleteObjects: 1.537600 ms)

DEBUG [Dissonance:Network] (23:11:52.602) MirrorIgnoranceCommsNetwork: Starting network session as Client
DEBUG [Dissonance:Recording] (23:11:52.721) CapturePipelineManager: Restarting transmission pipeline: 'Network mode changed'
DEBUG [Dissonance:Recording] (23:11:52.724) BasicMicrophoneCapture: GetDeviceCaps name=`` min=`44100` max=`44100`
[Dissonance:Recording] (23:11:52.779) BasicMicrophoneCapture: Began mic capture (SampleRate:44100Hz, FrameSize:882, Buffer Limit:2^13, Latency:20ms, Device:'')
DEBUG [Dissonance:Recording] (23:11:52.787) BasePreprocessingPipeline: Started preprocessor thread. Internal latency: 0ms, Total stream latency:20ms
DEBUG [Dissonance:Recording] (23:11:52.794) WebRtcPreprocessingPipeline: Resetting WebRtcPreprocessor
DEBUG [Dissonance:Recording] (23:11:52.798) WebRtcPreprocessingPipeline: Creating new preprocessor instance - Mob:False NS:High AEC:Low DelayAg:True Ext:True, Refined:True Aecm:Disabled, Comfort:True
DEBUG [Dissonance:Recording] (23:11:52.802) WebRtcPreprocessingPipeline: Exchanging preprocessor instance in playback filter...
DEBUG [Dissonance:Recording] (23:11:52.802) WebRtcPreprocessingPipeline: ...Exchanged preprocessor instance in playback filter
DEBUG [Dissonance:Recording] (23:11:52.802) WebRtcPreprocessingPipeline: Associated preprocessor with playback filter - but filter is not running
DEBUG [Dissonance:Recording] (23:11:52.806) BasePreprocessingPipeline: Resetting preprocessing pipeline
DEBUG [Dissonance:Recording] (23:11:52.914) BasicMicrophoneCapture: Trying to read 1344 samples, growing read buffer space to 2047
DEBUG [Dissonance:Core] (23:11:55.643) VoiceBroadcastTrigger: Recalculating token activation: 0 tokens, activated: True
DEBUG [Dissonance:Core] (23:11:55.647) RoomChannels: Opened channel to room 'Global'
DEBUG [Dissonance:Core] (23:11:55.647) LocalVoicePlayerState: Local player started speaking
DEBUG [Dissonance:Recording] (23:11:55.659) CapturePipelineManager: Subscribing encoder to preprocessor
DEBUG [Dissonance:Recording] (23:11:55.660) EncoderPipeline: Applying encoder reset
DEBUG [Dissonance:Network] (23:11:55.700) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (1 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.728) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (2 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.779) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (3 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.829) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (4 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.862) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (5 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.895) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (6 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.946) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (7 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:55.996) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (8 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.029) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (9 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.047) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (10 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.097) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (11 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.148) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (12 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.182) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (13 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.216) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (14 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.266) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (15 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.284) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (16 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.335) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (17 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.368) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (18 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.419) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (19 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:56.453) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (20 packets discarded so far)
DEBUG [Dissonance:Core] (23:11:56.504) RoomChannels: Closed channel to room 'Global'
DEBUG [Dissonance:Core] (23:11:56.504) LocalVoicePlayerState: Local player stopped speaking
DEBUG [Dissonance:Network] (23:11:56.503) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (21 packets discarded so far)
DEBUG [Dissonance:Recording] (23:11:56.522) EncoderPipeline: Requesting encoder stop
DEBUG [Dissonance:Recording] (23:11:56.522) CapturePipelineManager: Stopping encoder
DEBUG [Dissonance:Recording] (23:11:56.538) CapturePipelineManager: Waiting for encoder to send last packet
DEBUG [Dissonance:Network] (23:11:56.540) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (22 packets discarded so far)
DEBUG [Dissonance:Recording] (23:11:56.540) EncoderPipeline: Encoder stopped
DEBUG [Dissonance:Recording] (23:11:56.555) CapturePipelineManager: Unsubscribing encoder from preprocessor
DEBUG [Dissonance:Recording] (23:11:56.556) EncoderPipeline: Applying encoder reset
DEBUG [Dissonance:Core] (23:11:58.029) RoomChannels: Opened channel to room 'Global'
DEBUG [Dissonance:Core] (23:11:58.030) LocalVoicePlayerState: Local player started speaking
DEBUG [Dissonance:Recording] (23:11:58.046) CapturePipelineManager: Subscribing encoder to preprocessor
DEBUG [Dissonance:Recording] (23:11:58.046) EncoderPipeline: Applying encoder reset
DEBUG [Dissonance:Network] (23:11:58.065) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (23 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.099) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (24 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.133) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (25 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.183) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (26 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.217) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (27 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.250) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (28 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.285) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (29 packets discarded so far)
DEBUG [Dissonance:Network] (23:11:58.335) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (30 packets discarded so far)
DEBUG [Dissonance:Core] (23:11:58.350) RoomChannels: Closed channel to room 'Global'
DEBUG [Dissonance:Core] (23:11:58.350) LocalVoicePlayerState: Local player stopped speaking
DEBUG [Dissonance:Recording] (23:11:58.366) EncoderPipeline: Requesting encoder stop
DEBUG [Dissonance:Recording] (23:11:58.367) CapturePipelineManager: Stopping encoder
DEBUG [Dissonance:Recording] (23:11:58.383) CapturePipelineManager: Waiting for encoder to send last packet
DEBUG [Dissonance:Network] (23:11:58.385) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (31 packets discarded so far)
DEBUG [Dissonance:Recording] (23:11:58.385) EncoderPipeline: Encoder stopped
DEBUG [Dissonance:Recording] (23:11:58.400) CapturePipelineManager: Unsubscribing encoder from preprocessor
DEBUG [Dissonance:Recording] (23:11:58.400) EncoderPipeline: Applying encoder reset
OnApplicationQuit: stopped client
TelepathyTransport Shutdown()
DEBUG [Dissonance:Network] (23:11:58.936) MirrorIgnoranceCommsNetwork: Closing network session
DEBUG [Dissonance:Network] (23:11:58.938) SendQueue`1: Stopped network SendQueue (dropping 0 remaining packets)
[Dissonance:Network] (23:11:58.943) MirrorIgnoranceClient: Disconnected
DEBUG [Dissonance:Core] (23:11:58.945) Rooms: Left chat room 'Global'
DEBUG [Dissonance:Recording] (23:11:58.946) CapturePipelineManager: Destroying
DEBUG [Dissonance:Recording] (23:11:58.951) BasePreprocessingPipeline: Disposed pipeline
DEBUG [Dissonance:Recording] (23:11:58.952) WebRtcPreprocessingPipeline: Clearing preprocessor instance in playback filter...
DEBUG [Dissonance:Recording] (23:11:58.952) WebRtcPreprocessingPipeline: ...Cleared preprocessor instance in playback filter
Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
Loaded scene 'Temp/__Backupscenes/0.backup'
	Deserialize:            2.443 ms
	Integration:            7.770 ms
	Integration of assets:  0.003 ms
	Thread Wait Time:       16.440 ms
	Total Operation Time:   26.655 ms
System memory in use before: 135.4 MB.
System memory in use after: 127.0 MB.

Unloading 118 unused Assets to reduce memory usage. Loaded Objects now: 4012.
Total: 10.723400 ms (FindLiveObjects: 0.629100 ms CreateObjectMapping: 0.115500 ms MarkObjects: 9.146700 ms  DeleteObjects: 0.830600 ms)

Unloading 39 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 400.4 MB.
System memory in use after: 400.7 MB.

Unloading 38 unused Assets to reduce memory usage. Loaded Objects now: 4307.
Total: 10.444100 ms (FindLiveObjects: 0.526600 ms CreateObjectMapping: 0.119600 ms MarkObjects: 9.730200 ms  DeleteObjects: 0.066800 ms)

Server : 
Dedicated server mode : True
test
[Dissonance:Core] (23:05:15.969) DissonanceComms: Loading default playback prefab
[Dissonance:Core] (23:05:15.997) DissonanceComms: Starting Dissonance Voice Comms (6.4.1)
- Network: [DissonanceSetup(Clone) (Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceCommsNetwork)]
- Quality Settings: [Quality: High, FrameSize: Medium, FEC: True, DenoiseAmount: High, VoiceDuckLevel: 0,75]
- Codec: [Codec: Opus, FrameSize: 1920, SampleRate: 48kHz]
Finished loading scene in host mode.
StartHostClient called
New player connected. IP : localhost
New player connected. IP : ::1
Received request data from : 1234
Player disconnected. IP :
Destroying : Player(Clone)
New player connected. IP : ::1
Received request data from : 1234
Player disconnected. IP :
Destroying : Player(Clone)

**Comment by martindevans** [comment]
I can't reproduce this issue, I ran the Mirror demo scene in a server build and a client can connect fine. Could you try building the demo scene and seeing if it works for you? That will confirm if this is some kind of setup issue in your scene.

[Discord Link](https://discordapp.com/channels/631607020310495232/631607497760702483/691664464558293083)

**Comment by martindevans** [comment]
This turned out to be an issue with the way the `NetworkManager` was set up ([Discord discussion](https://discordapp.com/channels/631607020310495232/631607497760702483/691686553948258354)).
