### ISSUE TITLE
[help] Error while building for UWP, missing ARM .dll, where I can find it?

### ISSUE THREAD

**Issue by amfdeluca** [Placeholder-Software/Dissonance#186]
## Context
Missing ARM .dll plugin for UWP, how can i solve the issue? Can i get it somewhere?

## Expected Behavior
Building without errors

## Actual Behavior
Not building

## Steps to Reproduce
1. Build for UWP with architecture ARM
2. Trying to create app package on VS2019
3. Error

## Your Environment
Unity 2018.4.9f1, VS2019, 

- **Dissonance version used**: Dissonance 6.4.2

- **Unity version**: Unity 2018.4.9f1

- **Editor Operating System and version**: Microsoft Windows 10 Pro (x64)

- **Build Settings**: UWP, ARM

**Comment by martindevans** [comment]
The plugins for UWP/ARM should be located in `Assets/Plugins/Dissonance/Plugins/UWP/ARM` and there should be two of them: `opus.dll` and `AudioPluginDissonance.dll`. Are those files missing in your installation?

If they are there could you also check that the inspector show the files are set to be included in the UWP player build. Often the asset store installer can fail to install these settings correctly.

**Comment by FriskyBishop** [comment]
@martindevans im also having this issue when building for hololens 2

Assets/Plugins/Dissonance/Plugins/UWP/ARM does not exists in my version downloaded from the asset store (im using mirror networking version)

**Comment by martindevans** [comment]
I've just checked and the asset store definitely shows that those files should be included:

<img width="151" alt="firefox_2020-04-03_15-51-35" src="https://user-images.githubusercontent.com/177519/78373880-0e776680-75c3-11ea-9475-05af78a333d4.png">

Could you try a complete clean download from the asset store (make sure to restart the editor before downloading and installing). If that still doesn't get the files please send an email to martin@placeholder-software.co.uk with your invoice number and I can send you those files directly.

**Comment by amfdeluca** [comment]
I've solved the issue as Martindevans says, however, I was wondering if there was also a specific version for ARM64

**Comment by martindevans** [comment]
Since it seems like this issue is fixed I'll close it for now, don't hesitate to re-open it if there's still a problem :)

There's not a separate ARM64 DLL since Unity itself doesn't make the distinction between `ARM64`/`ARMv7a` architectures for UWP:

<img width="367" alt="2020-04-03_18-07-36" src="https://user-images.githubusercontent.com/177519/78386772-168cd180-75d6-11ea-9b2e-7c509493b970.png">
