### ISSUE TITLE
No Microphone input on OSX

### ISSUE THREAD

**Issue by Aiviator** [Placeholder-Software/Dissonance#189]
##  Context
When running the demo app for dissonance using darkrift2 free server on a mac no audio is transmitted from the Mac

## Expected Behavior
Audio is transmitted to connected clients

## Actual Behavior
No audio is transmitted from a mac, both on windows and linux it is working fine. It was tested on a different mac with High Sierra 10.13.6 with the same results.

## Workaround
Use a windows or linux system

## Steps to Reproduce
1. Install Dissonance voice chat
2. Install darkrift2 server
3. Install dissonance for darkrift2
3. Run the demo app on a linux machine and a mac machine and connect to darkrift2 server.
4. Tick the box in the left bottom corner : global chat enabled.

## Your Environment
- **Dissonance version used**:6.4.6
- **Darkrift version used**:2.5.0
- **Dissonance for darkrift2 version used**:6.4.6.1

- **Unity version**: 2019.3.8f1

- **Editor Operating System and version**: MacOSX catalina 10.15.4

- **Build Settings**: Mac OSX standalone

**Comment by martindevans** [comment]
Hi Aiviator

Someone on [Discord](https://discord.gg/8dKpP5W) has recently reported this same issue - in his case it was a permission issue. To quote:

> Found a solution. I've added the NSMicrophoneUsageDescription to the info.plist using a PostProcessBuild script.

We'll investigate to see if there's an easier way to do this and will update the documentation for MacOS platform requirements soon.

**Comment by martindevans** [comment]
I have updated the [relevant documention](https://dissonance.readthedocs.io/en/latest/Platforms/MacOS/index.html) to include a link to the Unity docs on permissions and the apple docs on the specific Microphone usage permission.
