### ISSUE TITLE
Unet LLAPI exception on client reconnect [bug] 

### ISSUE THREAD

**Issue by AndriusGergelis** [Placeholder-Software/Dissonance#19]
Hello,

I'm currently using Unity 5.5.0f3 and Dissonance 1.0.3, and ran into an issue:
1. Setup a simple LLAPI project as described in documents,
2. Starting server and client by calling InitializeAsClient() and InitializeAsSever(),
3. Stopping client by calling StopClient(),
4. Starting client once more while server is still running produces this log on server and voice chat breaks
![image](https://cloud.githubusercontent.com/assets/25668146/22794495/0e4b27f6-eefc-11e6-8b10-4e7c1ec8b910.png)

**Comment by martindevans** [comment]
Hi AndriusGergelis

Could you give me a little more information about the setup?

 - Are you calling InitializeAsClient and InitializeAsServer on two different peers (i.e. one as client, one as server)?
 - Assuming you are running two peers, which do you call StopClient on?
 - What's your code for starting the client again?
 - Could you post a more detailed log, to do this click on "Diagnostic Settings" in your DissonanceComms component and set everything to "**Trace**" (this has a serious performance implications - remember to set them back to "**Info**" afterwards!)

**Comment by AndriusGergelis** [comment]
Ran client and server on different peers and called StopClient() on peer which had ClientEnabled flag set to true. I start client by calling InitializeAsClient(address). Setting log levels to "Trace" did not produce any valuable info. Attached a simple project, with which I was able to reproduce the issue. 
[disonance-test.zip](https://github.com/Placeholder-Software/Dissonance/files/764561/disonance-test.zip)

**Comment by martindevans** [comment]
Thanks for the project, I can confirm that reproduces the problem. I'm looking into it now :)

**Comment by AndriusGergelis** [comment]
Thank you for such a fast response. Would really appreciate a workaround or a fix as soon as possible, the deadline is very near :D

**Comment by martindevans** [comment]
I actually already identified (at least part of) the problem although I don't have a proposed fix/workaround for it yet.

Line 59 of UNetServer.cs is:

```
case NetworkEventType.DisconnectEvent:
    ClientDisconnected(senderConnectionId);
```

This tells the server that the given client has disconnected and the server cleans up it's internal datastructures to remove all reference to that client. This event never happens! This is particularly odd because it's part of UNet which invokes that event...

**Comment by martindevans** [comment]
Hello again.

We've got a workaround for this problem. Simply add this code into UNetClient.cs:

```
public override void Disconnect()
{
    base.Disconnect();
    byte error;
    NetworkTransport.Disconnect(_socket, _connection, out error);

    if (error != (int) NetworkError.Ok)
        Log.Error("Failed to cleanly disconnect from Dissonance server at {0}:{1}, Error {2}", _network.ServerAddress, _network.Port, (NetworkError) error);
}
```

If that resolves the problem, please close this issue.

**Comment by AndriusGergelis** [comment]
It did resolved it, thank you very much. Glad we bought this asset.
