### ISSUE TITLE
[Log Error] [Dissonance:Playback] (17:10:41.949) EncodedAudioBuffer: Voice Error: Encoded audio heap is getting very large (40 items)! Error ID: 59EE0102-FF75-467A-A50D-00BF670E9B8C

### ISSUE THREAD

**Issue by cliv3dev** [Placeholder-Software/Dissonance#192]
## Context
When a host (on Editor) and a client (on Oculus Quest) are connected together through WAN connxexion (WiFi->4G shared connexion by an iPhone for the Client and Ethernet->Optic fiber for the Host), I can get those errors on the Editor log as well as the Quest log. There was no discussion at the time, only background noise.

## Expected Behavior
Should not have those logs

## Actual Behavior
during connexion of less than 1 minute, this error was logged 3 times.

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. start a host on Win Editor with Unity 2019.3.11f1 and Mirror 12.12.0 and Thelepathy transport
2. start a client on Oculus Quest with same Unity version player and mirror and data
3. wait for connexion
4. let the 2 devices run for some time

## Your Environment
Host: Windows 10, Unity 2019.3.11f1, i9, 16Gb RAM, GTX1960, ethernet connexion to Optic fiber box
Client: Oculus Quest with v16 OS connected to iphone 8 with shared connexion to 4G network

- **Dissonance version used**: e.g. v1.0.0 _(check Assets/Dissonance/changelog)_
v6.4.6
- **Unity version**: e.g. 5.3.5f1 Personal _(check Help > About Unity)_
Unity 2019.3.11f1,

- **Editor Operating System and version**: e.g. Microsoft Windows 10 Pro 10.0.10586 (x64) 
Win10 Pro, 18362.778 (x64)

- **Build Settings**: Tell us the build settings/platforms you have encountered this issue with e.g. Windows, x86_64, Development Build
Oculus Quest/Android ARM64, IL2CPP, Master, no Dev build, LZ4HC
[Quest Realcast-Avatars Log.txt](https://github.com/Placeholder-Software/Dissonance/files/4588350/Quest.Realcast-Avatars.Log.txt)

- **Link to your project**: If your project (or a bug reproduction project) is available, link it here

**Comment by cliv3dev** [comment]
[WinEditor(Host) Realcast-Avatars Log.txt](https://github.com/Placeholder-Software/Dissonance/files/4588368/WinEditor.Host.Realcast-Avatars.Log.txt)

**Comment by martindevans** [comment]
The log shows this message: `EventQueue: Large number of received packets pending dispatch (26)` which indicates that 26 packets of data arrived from the network within the same frame! This will cause the `Encoded audio heap is getting very large` error. There could be some kind of network error, or a large delay (e.g. extremely low frame rate) on the sending side causing all these packets to buffer up. This could be caused by the Telepathy backend that you're using - telepathy isn't _really_ supported for voice because it's TCP but voice needs unreliable packets (i.e. UDP). Using a TCP connection can make small network errors much worse (e.g. a small interruption causes a large backlog in packets).

Could you try upgrading to Dissonance 7.0.1 (released yesterday) and running the demo scene with the Ignorance Mirror backend. If the problem persists please increase the Dissonance log level to `Debug` for all categories and send me another log.

**Comment by cliv3dev** [comment]
I can't use Ignorance, since they don't seem to support HoloLens2 platform (UWP). But I can test with LiteLNetLib4Mirror which has an unreliable UDP channel...

**Comment by martindevans** [comment]
LiteNetLib4Mirror should work just as well as ignorance :)

**Comment by cliv3dev** [comment]
Switched to LiteNetLib4mirror and testing localy on the same PC : Editor/Host and a standalone/Client on local network.
I have those errors:
[Dissonance:Playback] (20:10:14.125) EncodedAudioBuffer: Error: Received a very late packet (41 packets late)! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: 30EF1B03-7BBC-49D3-A23E-6E84781FF29F
Had this warning in the log 6 times in a row.

**Comment by martindevans** [comment]
Can you reproduce this error in the Mirror demo scene? usually an overflowing buffer like this indicates one of three things:

 - Performance issues on the sending side - low frame rate caused a lot of audio to be sent at once, overflowing the receive buffer.
 - Network level issue - lots of packets were buffered up in the network for some reason (e.g. congestion)
 - Performance issues on the receiving side - e.g. low frame rate causes audio playback to fall behind.

In your test (local network to same PC) I think we can safely eliminate a network level error. So it could be a performance issue in your scene (if look look in the profiler don't look at overall _average_ frame rate, instead look at the worst frame times). Also check that you have `Run In background` enabled!

**Comment by martindevans** [comment]
Hi cliv3dev, did you make any progress reproducing this error in a simpler scene?

**Comment by cliv3dev** [comment]
Sorry Martin, didn’t take the time to reproduce it…

Cheers,


________________________________
De : Martin Evans <notifications@github.com>
Envoyé : Thursday, June 4, 2020 5:11:25 PM
À : Placeholder-Software/Dissonance <Dissonance@noreply.github.com>
Cc : Diego Fernandez-Bravo <diego@realcast.io>; Author <author@noreply.github.com>
Objet : Re: [Placeholder-Software/Dissonance] [Log Error] [Dissonance:Playback] (17:10:41.949) EncodedAudioBuffer: Voice Error: Encoded audio heap is getting very large (40 items)! Error ID: 59EE0102-FF75-467A-A50D-00BF670E9B8C (#192)


Hi cliv3dev, did you make any progress reproducing this error in a simpler scene?
