### ISSUE TITLE
Unet LLAPI playback issues after scene load

### ISSUE THREAD

**Issue by AndriusGergelis** [Placeholder-Software/Dissonance#20]
Hi,

ran into another issue while integrating dissonance into our project. After loading larger scene on one of the peers stops replaying voice. Steps to reproduce the issue:
- Download project [https://drive.google.com/file/d/0B3YtCSWyMqhTVVd1bTFucjBLWTQ/view?usp=sharing](url),
- Run 2 peers and press 'Host' on one and 'Join' on the other,
- Press 'LoadLevel' on one of the peers,
- 'Scene loaded' should appear on the screen.

At this point one of the peers voice playback stops entirely or it becomes quite distorted.

My environment:
- Unity 5.5.0f3
- Dissonance 1.0.3

**Comment by TomGillen** [comment]
Thanks for the repro, I'll take a look at this and get back to you.

**Comment by AndriusGergelis** [comment]
I think I overdid the large scene 'simulation' and fps drops way to low. I will provide a better example when I will be able to.

**Comment by TomGillen** [comment]
Deleting the cubes after the large scene has loaded (which brings the fps back up) does not resolve the issue, so the problem is not the fps alone.

**Comment by AndriusGergelis** [comment]
I was not able to reproduce it after deleting cubes,

**Comment by AndriusGergelis** [comment]
For me it occurs at random. Sometimes it works just fine.

**Comment by AndriusGergelis** [comment]
Any new regarding this issue? Our deadline is near, we would like to fix this asap.

**Comment by martindevans** [comment]
Hi Andrius, sorry for the delay on this - Tom is still working to identify the core problem.

It's not a complete fix but he has made a number of changes to the playback system to mitigate the worst effects. If you send your invoice number to martin@placeholder-software.co.uk I'll send you the latest release candidate which includes these changes.

**Comment by martindevans** [comment]
Hi again Andrius,

Was the fix in the test version satisfactory? If so feel free to close this issue, if not please leave us some feedback on what more needs to be done :)

**Comment by AndriusGergelis** [comment]
Hi Martin,

I'm currently on a business trip.  I will reply as soon as I get back.

**Comment by AndriusGergelis** [comment]
Hi,

I found some time to test new build you've send me. Locally, I could not reproduce the issue and for now I'm closing it. In the future we will test it with more people and if we'll find any issue I'll provide you with feedback. Thank you for great support.

**Comment by martindevans** [comment]
Thanks Andrius, Glad we could help :)
