### ISSUE TITLE
[help] ARM64 error on Hololens 2

### ISSUE THREAD

**Issue by amfdeluca** [Placeholder-Software/Dissonance#201]
## Context
I would like to know if there is a possibility to build for ARM64. At the moment it seems to me that there is only the possibility to build for ARM. In fact, with ARM I have no problem but if I try to build for ARM64 I have several errors due to the lack of the plugin.

![Screenshot (12)](https://user-images.githubusercontent.com/56428422/84992255-f4700d80-b147-11ea-9a13-f313063341be.png)
![Screenshot (13)](https://user-images.githubusercontent.com/56428422/84992258-f5a13a80-b147-11ea-9bf1-9364103aa53e.png)

## Expected Behavior
Build for ARM64 gives no error

## Actual Behavior
Error when building for ARM64

## Your Environment

- **Dissonance version used**: 6.4.6

- **Unity version**: 2019.4.0

- **Editor Operating System and version**: Hololens 2

- **Build Settings**: ARM64

**Comment by martindevans** [comment]
The plugins in the UWP/ARM directory should work on both the ARM and ARM64 platforms. If you change `CPU:ARM` to `CPU:ARM64` in that dropdown it should work for hololens 2.

**Comment by martindevans** [comment]
Hi @amfdeluca  did you ever manage to get this working? I'll close this issue for now since it's been a while but feel free to re-open it if you still need help :)
