### ISSUE TITLE
Hololens 2

### ISSUE THREAD

**Issue by martindevans** [Placeholder-Software/Dissonance#205]
Two people have reported that Dissonance needs ARM64 binaries to work on Hololens 2. This wasn't a requirement in previous versions of Unity, but presumably something has changed in a newerversion of the editor.

Recompile `opus.dll` and `AudioPluginDissonance.dll` for ARM64 and include them in the next update.

 - [x] Recompile Opus.dll
 - [x] Recompile AudioPluginDissonance.dll
 - [x] Confirm with Silloty/rje (on Discord) that these work on the actual device.

**Comment by pygd-ysb** [comment]
Hololens 2 Build failed with some exceptions.

![dissonance error](https://user-images.githubusercontent.com/45594787/95292655-dff98180-08ac-11eb-813c-5683d1b5db25.PNG)


So, I changed the settings like this:

ARM64/AudioPlguinDissonance.dll
[SDK] : Any SDK
[CPU] : ARM
[Don't process] : false -> true

then another error occurs.

![dissonance error2](https://user-images.githubusercontent.com/45594787/95292687-ed167080-08ac-11eb-81bb-873746a01e14.PNG)


I changed again:

ARM64/opus.dll
[SDK] : UWP -> Any SDK
[CPU] : ARM
[Don't process] : false -> true

After Changing the two files, the build was successful.
But when i run the app an exception occurred.

![dissonance error4](https://user-images.githubusercontent.com/45594787/95292717-fd2e5000-08ac-11eb-8f03-e3999d95c003.PNG)


Same thing happened after changing CPU to ARM64.

HEEEEELP


==========

Environment

Windows 10 pro
Unity (2019.4.9f personal)
Visual studio (2019)
Dissonance (7.1.2)
Photon unity network 2 (2.22)
MS Mixed Reality Toolkit (2.4.0 and 2.5.0)

Build through MRTK Build Window

![dissonance error3](https://user-images.githubusercontent.com/45594787/95292735-06b7b800-08ad-11eb-9908-1b1626bcbdc1.PNG)

**Comment by martindevans** [comment]
Hi @pygd-ysb - could you post some screenshots of what your import settings look like for the two plugins? Could you also check the build result to see if the correct files have been copied into the build output? Thanks.

**Comment by martindevans** [comment]
While I'm waiting for an answer to the previous question, I tested out some tweaks to the import settings locally. As far as I can tell they should look like this:

<img width="456" alt="Unity_2020-10-07_17-07-44" src="https://user-images.githubusercontent.com/177519/95357448-c57cd380-08bf-11eb-8ab6-5a10f111360d.png">
<img width="453" alt="Unity_2020-10-07_17-07-56" src="https://user-images.githubusercontent.com/177519/95357456-c877c400-08bf-11eb-83f4-be6a1daaa772.png">

These settings build correctly. I don't have a hololens so unfortunately I can't test them :(

**Comment by davidjbain** [comment]
Just tested on my hololens 2 with your plugin settings, seems to work normally for me!

**Comment by pygd-ysb** [comment]
Sorry for late.
I tried again the next day with the same settings and it works well. 😂

**Comment by martindevans** [comment]
This was released a while ago, I forgot to close the issue.
