### ISSUE TITLE
[bug] Positional tracking respects distance falloff but not directional panning (HLAPI)

### ISSUE THREAD

**Issue by HadynTheHuman** [Placeholder-Software/Dissonance#22]
## Context
Positional audio with the Dissonance HLAPI integration is panning evenly between left and right speakers/headphones regardless of the source's relative location to the listener - though distance falloff otherwise works as expected. The source is definitely configured correctly; if I manually play an audioclip through it, it respects both distance and direction - it's only voice which loses the directional information.

## Expected Behavior
Positional audio should pan to the left/right channel based on the relative direction between source and listener.

## Actual Behavior
Positional audio does not pan to the left/right channel based on the relative direction between source and listener.

## Fix
Untested, but I did some digging and discovered a seemingly relevant Unity thread for "OnAudioFilterRead sound spatialisation" with the following suggestion:
"make the AudioSource play a short looping audio clip where every sample point has a value of not 0, but 1. Make your audio filter multiply the original sample value with the one you're generating, rather than overwriting it. That way, the Audio Source's panning and volume will be applied, including the rolloff."
https://forum.unity3d.com/threads/onaudiofilterread-sound-spatialisation.362782/

## Steps to Reproduce
This is fairly straightforward, but what the heck:
1. Load the HLAPI Integration demo.
2. Create a custom playback prefab with a 3D audio source.
3. Run the project over a network, test speaking to the left and right of the listener and/or having the listener spin around whilst receiving voice.

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: 1.0.5

- **Unity version**: 5.5.1f1

- **Editor Operating System and version**: Microsoft Windows 10 Pro (x64)

**Comment by martindevans** [comment]
Hi HadynTheHuman, thanks for the detailed bug report!

Someone else reported this issue recently and we already have a fix for it in our development version. Just to make sure you're reporting exactly the same issue: audio falls off with distance correctly, but does not pan - is that correct?

If you send me your invoice number ([martin@placeholder-software.co.uk](mailto://martin@placeholder-software.co.uk)) I'll send you a copy of that new version.

**Comment by HadynTheHuman** [comment]
Hi Martin. Thanks - and yes, that's all correct :)

I've just sent you an email.

**Comment by martindevans** [comment]
Dissonance 1.0.6 just went live on the asset store. That includes a fix for this problem so I'll close this issue - of course feel free to re-open it if things aren't satisfactory.
