### ISSUE TITLE
Oculus Quest 2 No Audio issue

### ISSUE THREAD

**Issue by JamesMillsDev** [Placeholder-Software/Dissonance#220]
## Context
Using Oculus Quest 2, the microphone does work with Unity as tested with just making it play back to myself using a simple script, however nothing is sent over the network, and Dissonance might not be opening the mic on the Oculus correctly, but due to having to build to test this issue because it's Android, I cannot say for certain.

## Expected Behavior
Dissonance should be broadcasting the microphone across the network.

## Actual Behavior
Nothing is captured or sent

- **Dissonance version used**: v7.1.5

- **Unity version**: 2019.3.6f1 - Unity Plus

- **Editor Operating System and version**: Windows 10 Version	10.0.19041 Build 19041

- **Build Settings**: Android - Oculus Quest 2

**Comment by JamesMillsDev** [comment]
Upon further investigation, it doesn't appear to be working on the rift either when Unity is set to Android, so maybe it's something to do with opening the mic on an Oculus?

**Comment by martindevans** [comment]
Could you turn the logging settings up to `Debug` for all categories in `Window > Dissonance > Diagnostics` and share a log from the Quest? That should show if Dissonance is trying to open the mic, and if it thinks it has succeeded.

**Comment by JamesMillsDev** [comment]
[Editor.log](https://github.com/Placeholder-Software/Dissonance/files/5798468/Editor.log)

**Comment by martindevans** [comment]
(discussed further on Discord and resolved the issue).
