### ISSUE TITLE
Eacho when 2 player in same room and close to each other

### ISSUE THREAD

**Issue by HarshitBhatt008** [Placeholder-Software/Dissonance#225]
I am getting echo when 2 user are in same room and they are close to each other is it any solutions to reduce it ?
when 2 user are close to each other their colliders are triggered and they are in same room that's why i am receiving duplicate/echo sound.

**Comment by martindevans** [comment]
The solution for this is to set up `Acoustic Echo Cancellation`. Relevant docs: https://placeholder-software.co.uk/dissonance/docs/Tutorials/Acoustic-Echo-Cancellation.html

**Comment by HarshitBhatt008** [comment]
Thanks for support. I will try and get back to you...
