### ISSUE TITLE
Opus error after building to Hololens 2 

### ISSUE THREAD

**Issue by ralphsayah** [Placeholder-Software/Dissonance#226]
Hey admins

Thanks for providing such asset. Looking forward to try it.. However after that my team and I installed the package, and followed all steps on your website to configure the settings, we tried building on Hololens 2.

We got the following error, therefore the build failed:

![image](https://user-images.githubusercontent.com/79223375/112336827-15145780-8cc6-11eb-950b-3ecb87d41419.png)

- **Unity version**: 2019.4.15f1

- **Build Settings**: ARM64 (for Hololens)

We kindly request your support asap since honestly our workflow highly depends on the success of this phase.

**Comment by martindevans** [comment]
In Assets/Plugins/Dissonance/Plugins/UWP there are 4 folders for the different platforms, each of those folders contains an opus.dll

<img width="327" alt="Unity_2021-03-24_15-56-23" src="https://user-images.githubusercontent.com/177519/112343324-eb096800-8cba-11eb-89e2-0cd0af18634d.png">

Please make sure that the settings for those should all have the same SDK, Scripting Backend and Don't Process settings (as shown above). Also make sure that the CPU setting corresponds to the folder name.
