### ISSUE TITLE
[Bug] - Dissonance doesn't seem to let go of audio resources

### ISSUE THREAD

**Issue by Sckir** [Placeholder-Software/Dissonance#229]
## Context
In our project we have to support more than one VoIP Solution. When we start a VoIP session with Dissonance there seems to be no issue at all, when we start one with VoIP#2 no issue either. 

But, if we start with Dissonance and then switch over to VoIP#2 we get strange "popping sounds" on the microphone.

## Expected Behavior
VoIP is clear on both services regardless of previously having created a session with Dissonance or not.

## Actual Behavior
If we start a Dissonance VoIP session and then move on to VoIP#2 we get a popping sound on the microphone and not the other way around.

## Fix
Speculation leads me to believe that upon closing the session Dissonance isn't letting go of the input/ouput resources in Unity.

- **Dissonance version used**: lattest
- **Unity version**: 2019.4

- **Editor Operating System and version**: e.g. Microsoft Windows 10 Pro 120.2212.2020.0(x64) 
- 
- **Build Settings**: We support several platforms all have the issue, PC, mobile android and iOS, MacOS, VR headsets

**Comment by martindevans** [comment]
Hi Sckir, did you manage to fix this?

**Comment by RicardoAlmeida-IVRE** [comment]
So when you create your audio clip and set a callback to feed data into it, would be my first guess as to the root.

We solved this by forcing the next created clip to be zeroed out.

Seems like even after shutting down a Dissonance channel and destroying every unneeded object there was data left on the buffer which would be dumped in the next audio clip.
