### ISSUE TITLE
NullReferenceException spam when disconnecting mid-transmission in HLAPI

### ISSUE THREAD

**Issue by HadynTheHuman** [Placeholder-Software/Dissonance#23]
I think I've discovered another small bug, but I'm a little short on time so this will be brief. If you have trouble reproducing the issue, let me know - I'm happy to come back and fill in more detail later on.

I've noticed the Unity console gets spammed with NullReferenceExceptions if I disconnect from the network session _during_ a voice transmission. Can reproduce by holding down the push-to-talk button whilst NetworkManager.StopServer() / StopClient() / StopHost() is called on either the client or host.

**Comment by martindevans** [comment]
Thanks for the report Hadyn. I'll try to reproduce this one and get back to you later :)

**Comment by martindevans** [comment]
Hi Hadyn,

I just tried to reproduce this issue and can't. I tried permanently transmitting on the server and listening on a client. I ran two tests, one disconnecting the client (while the server transmits constantly) and one disconnecting the server (while it is still transmitting). Both result in a few warnings I will investigate, but no null reference exception.

**Comment by HadynTheHuman** [comment]
Hi Martin,

No worries, I'll try to build a simplified repro scene to share with you whenever I get some time in the office this week.

**Comment by martindevans** [comment]
A repro project would be fantastic! Before you expend all that effort feel free to just post a stacktrace on here, I may be able to work it out just from that :)

**Comment by HadynTheHuman** [comment]
My apologies Martin, it seems the issue was on my end; at some point the NetworkIdentity got detached from my dissonance manager object. I've put it back and the spam is gone :)

That said, I may have noticed another issue; I'm not getting any sound through Dissonance at all when a client disconnects/reconnects, or even when a single person hosts their own session, ends it, and then hosts another. I've just double-checked by testing this in the clean HLAPI demo scene after a fresh install of Dissonance 1.0.6, and was able to reproduce the bug without changing anything in that scene.

**Comment by HadynTheHuman** [comment]
In the meantime, it looks like I can work around the issue by destroying and re-instantiating the dissonance manager object whenever StopHost() is called.

**Comment by martindevans** [comment]
> it seems the issue was on my end

No worries :)

> disconnects/reconnects

That makes sense, the DissonanceComms object isn't meant to live between network sessions. This is our fault for being lazy and using a NetworkIdentity in the demo scene - really it should be a "loading scene" which sets up the networking and then loads a "game scene" which runs the game (and contains Dissonance).

I'll mark this issue as a medium priority bug for now - we're planning to do a pass over the demo scenes to make them far more comprehensive in the future and this issue will be covered by that.

**Comment by martindevans** [comment]
The new release of Dissonance (1.1.0) was just submitted to the store. This release includes brand new demo scenes which demonstrate how to properly use Dissonance to avoid this issue. If you'd like to get a copy of this version before it's available on the store please email martin@placeholder-software.co.uk your order number.

**Comment by martindevans** [comment]
1.1.0 is now live with a fix for this so I'll close this issue. Please don't hesitate to re-open the issue if it is still a problem :)
