### ISSUE TITLE
[Bug] I stop hearing players after some time in room, when i press record button I start hearing others again

### ISSUE THREAD

**Issue by friuns2** [Placeholder-Software/Dissonance#235]
Voice chat stops working after a while, after pressing speak button starts work again

this happens when i press record button

![image](https://user-images.githubusercontent.com/16543239/130023438-65da13cd-45e1-491a-a6c3-4bca8d943db4.png)

![image](https://user-images.githubusercontent.com/16543239/130023885-cdd2e143-4fa4-4bd4-a18f-80cd9b63c908.png)

2019.4.17f dissonance 8.0.1 and 7.1.0

**Comment by martindevans** [comment]
Hi, could you send me the complete log from when this happens? Thanks.

**Comment by friuns2** [comment]
I revered back to 7.1.0 so its log from that version.  
  
Happens always when Master client leaves and new master client assigned. 

https://gist.github.com/friuns2/3b58b6b717829b60308dda378cd386a2

**Comment by friuns2** [comment]
hm looks like i solved it wasn't dissonance related issue
