### ISSUE TITLE
[feature]Forge Networking Remastered Integration

### ISSUE THREAD

**Issue by mcguinnessdr** [Placeholder-Software/Dissonance#24]
Hello, I am using Forge Networking Remastered, and was hoping that an integration for it could be created. I tried making my own, but I haven't been able to get it to work so far. Attached is my attempt, hopefully you will be able to fill in the missing pieces for me. Thanks!
[ForgeRemastered.zip](https://github.com/Placeholder-Software/Dissonance/files/908733/ForgeRemastered.zip)

**Comment by mcguinnessdr** [comment]
I think this is pretty close, still not sending the voice packets across though.
[ForgeRemastered.zip](https://github.com/Placeholder-Software/Dissonance/files/908991/ForgeRemastered.zip)

**Comment by martindevans** [comment]
Hi mcguinnessdr

I'll have a look at this now.

Long term we plan to collaborate with bearded man studios to write a complete forge remastered integration (we're just waiting for some time in both of our timetables to work on it).

**Comment by martindevans** [comment]
I should mention I don't have a copy of Forge Remastered to test with at the moment. The overall code looks pretty good, it looks like you've just made a couple of mistakes:

#### ForgeRemasteredServer: Line 28, 37 and and ForgeRemasteredClient: Line 44, 49

```new BeardedManStudios.Forge.Networking.Frame.Binary(NetworkManager.Instance.Networker.Time.Timestep, false, packet.Array, Receivers.All, _network.SystemMessagesChannelToServer, true);```

 - You're sending the entire `packet.Array`, this is going to break for two reasons:
   - The start of the array is not necessarily the start of the data (you need to respect packet.Offset). If this is wrong it will not work at all.
   - You're sending the entire buffer but Dissonance deliberately uses very large buffers to ensure it never runs out of space. If this is wrong performance will completely suck.

You may need to ask the forge guys how best to write a *part* of an array into a `Frame.Binary`. In the basic Forge integration we use: `_sendBuffer.BlockCopy(packet.Array, packet.Offset, packet.Count);` but I don't know if that's still something you can use.

 - You have the channels backwards:
   - On the server you're using `_network.SystemMessagesChannelToServer` but you need to use `_network.SystemMessagesChannelToClient`
   - On the client you're using `_network.SystemMessagesChannelToClient` but you need to use `_network.SystemMessagesChannelToServer`

Pay close attention to the naming scheme, the server sends **to** clients and client send **to** the server. Once you know that you can't get them mixed up :)

#### ForgeRemasteredServer: Line 55 and ForgeRemasteredClient: Line 33

```
//todo: Idk what the second argument is actually supposed to be
base.NetworkReceivedPacket(new ForgeRemasteredPeer(player), new ArraySegment<byte>(frame.StreamData.byteArr, 0, frame.StreamData.byteArr.Length));
```

It looks like `StreamData` is a `BMSByte` which is what the basic Forge integration works with. So I guess you could probably use the same code as Dissonance uses for that:

```
new ArraySegment<byte>(frame.StreamData.byteArr, frame.StreamData.StartPointer, frame.StreamData.Size);
```

**Comment by mcguinnessdr** [comment]
Thanks, I noticed my mistake with the channels last night. I'll make the rest of the changes and see if that does it.

**Comment by mcguinnessdr** [comment]
Thanks for the help, got it all working!
[ForgeRemastered.zip](https://github.com/Placeholder-Software/Dissonance/files/911374/ForgeRemastered.zip)

**Comment by martindevans** [comment]
Excellent!
