### ISSUE TITLE
[bug] iOS Crash when i build with plugin Insta360 camera

### ISSUE THREAD

**Issue by marksTam201** [Placeholder-Software/Dissonance#240]
## Context

I use Dissonance HLAPI and plugin Insta360 Camera in my project, it work fine on Android but when I build for IOS,
It always crash when I try use BasicMicrophoneCapture and SendFrame.
If i setting Activation Mode = none --> no crash app, but can not chat voice, it is ultimately impractical.

## Your Environment
Include as many relevant details about the environment you experienced the bug in

- Dissonance HLAIP: 8.0.0
- Camera360SDK- IOS:   INSCameraSDK 2.7.15, INSComedia 1.25.9
Link: [https://github.com/Insta360Develop/CameraSDK-iOS](url)
- Unity version: 2018.4.21
- Xcode 15
- IOS 14.7

![image](https://user-images.githubusercontent.com/6201864/136644320-cb2432c6-24ce-4f93-9657-e0dd11f98282.png)
![image](https://user-images.githubusercontent.com/6201864/136644357-2cf1af3b-1290-48ee-97c9-f355547d8c0b.png)

**Comment by marksTam201** [comment]
Hi, we have to stop using insta360 now to be able to use dissonance on Ipad.
I want to ask more, does dissonance use webrtc and is the outgoing voice data encrypted?

**Comment by martindevans** [comment]
> does dissonance use webrtc?

Dissonance does use components of webrtc, but only for audio processing not for networking.

> is the outgoing voice data encrypted?

Dissonance itself does not do encryption, that should be done in the network backend. It looks like HLAPI (which is the backend you're using I think?) does have support for encryption plugins ([docs](https://docs.unity3d.com/Manual/UNetEncryptionPlugins.html)), so you may want to look into that

**Comment by martindevans** [comment]
Since it sounds like you're not using the camera any more and they never responded, I'll close this one for now.
