### ISSUE TITLE
Updating to latest unity version causing some issues

### ISSUE THREAD

**Issue by FedericoStefan** [Placeholder-Software/Dissonance#245]
Follow up of this page: https://github.com/Placeholder-Software/Dissonance/issues/244

So updating caused these three issues (I updated to the latest Unity 2021 version available)
`Server\ServerRelay.cs(68,20): error CS0029: Cannot implicitly convert type 'void' to 'System.ArraySegment<byte>'`
`Client\PeerVoiceReceiver.cs(119,21): error CS0815: Cannot assign void to an implicitly-typed variable`
`Playback\DecoderPipeline.cs(141,17): error CS0815: Cannot assign void to an implicitly-typed variable`

The first error leads to this:
`data = data.CopyTo(data.Array);`
The second error:
`var frame = reader.ReadByteSegment().CopyTo(_byteArrPool.Get());`
The last/third error:
`var frameCopy = packet.EncodedAudioFrame.CopyTo(_bytePool.Get());`

**Comment by martindevans** [comment]
These errors are all caused by Unity adding a new method `CopyTo` which has a _different_ signature to a `CopyTo` method we had already created.

They should all be fixed in the latest version of Dissonance. If you'd rather not upgrade Dissonance for some reason you may be able to replace all those `CopyTo` calls with `CopyToSegment` which is our new replacement (that method may not exist if you're on a really old version of Dissonance).

**Comment by FedericoStefan** [comment]
Fixed it. also follow up to the past forum i still cant hear other people.
The playback prefab has this.
![Screenshot_449](https://user-images.githubusercontent.com/64701524/144284432-c361fe08-2b8e-4e20-8e7f-9d951ffbad19.jpg)

**Comment by martindevans** [comment]
Does the demo scene work?

**Comment by FedericoStefan** [comment]
> `CopyToSegment`

Hang on, I will try now.

**Comment by FedericoStefan** [comment]
> Does the demo scene work?
> 
> Edit: Just a note that "No Active Session" in this context means "not currently speaking", it's nothing to do with the network session (that often confuses people).

I will try now

**Comment by FedericoStefan** [comment]
> Does the demo scene work?
> 
> Edit: Just a note that "No Active Session" in this context means "not currently speaking", it's nothing to do with the network session (that often confuses people).

It still doesnt work sadly.

**Comment by FedericoStefan** [comment]
Wait it actually works @martindevans ! But i hear the audio i think distorted? It doesnt show active session but some packets and other stuff, so it means it works but i hear a clicking sound when players start speaking and stop speaking, and i dont hear them.

Heres a video showing the issue (I think its caused due to the audio being really loud even though it isnt?

https://user-images.githubusercontent.com/64701524/144314346-222a0eca-1ece-4d66-bed8-79237616ee47.mp4

)

**Comment by martindevans** [comment]
On your other issue you mentioned that you're using Dissonance **V6.4.1**. This is a _very_ old version and we've fixed a lot of bugs since then! Can you upgrade to the latest version (8.0.3) to see if that fixes it?

**Comment by FedericoStefan** [comment]
I'm going to try to, my project is 130gb or more lol. So it will take a while.
