### ISSUE TITLE
Is hololens2 in arm64 supported?

### ISSUE THREAD

**Issue by shoukailiang** [Placeholder-Software/Dissonance#249]
Is hololens2 in arm64 supported?

**Comment by martindevans** [comment]
It should be, yes. If you're having trouble with deploying to the Hololens check that the plugins in `Assets/Plugins/Dissonance/Plugins/UWP/ARM64` have the correct settings.

**Comment by martindevans** [comment]
I'll assume everything's working for you, don't hesitate to comment if you've got any issues with Dissonance+Hololens2 :)
