### ISSUE TITLE
[bug] 'AudioPluginDissonanceNative' does not contain a definition for 'Dissonance_SetMinBandGain' on 8.2.0 for macOS

### ISSUE THREAD

**Issue by jhorikawa** [Placeholder-Software/Dissonance#256]
## Context
When I imported Dissonance Voice Chat 8.2.0 on Unity 2021.3.0f1 with macOS 12.4 I got an error saying as follows.

`Assets/Plugins/Dissonance/Core/Audio/Capture/WebRtcPreprocessingPipeline.cs(491,53): error CS0117: 'AudioPluginDissonanceNative' does not contain a definition for 'Dissonance_SetMinBandGain'`

## Expected behaviour
I didn't see this error message when the version was 8.1.0. 

## Actual behaviour
Error when importing Dissonance Voice Chat 8.2.0 on Unity 2021.3.0f1 with macOS 12.4.

## Workaround
Couldn't find workaround.

## Fix
Couldn't find fix

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. Create new project on Unity 2021.3.0f1.
2. Import Dissonance Voice Chat 8.2.0 through Package Manager.

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: v8.2.0 (2022-07-21)

- **Unity version**: 2021.3.0f1

- **Editor Operating System and version**: macOS 12.4 with M1 mac

- **Build Settings**: macOS, Intel 64-bit + Apple silicon

**Comment by martindevans** [comment]
Tom has been investigating this today, we plan to push out an urgent fix first thing on Monday.

As a workaround, in `Assets/Plugins/Dissonance/Core/Audio/Capture/AudioPluginDissonanceNative.cs` add this method on line 43:

```csharp
public static void Dissonance_SetMinBandGain(IntPtr state, float min_band_gain)
{
}```

**Comment by martindevans** [comment]
Dissonance 8.2.1 has just released which includes a hotfix for this issue.
