### ISSUE TITLE
trying to send voice packets with websocket (customNetworking)

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#259]
hello dear friends
im trying to send voice packets with websocket, is it possible?
i cant undrestand how should transfer packets in websocket.
i think should convert ArraySegment<byte> packet to string or base64 or.. and after receive in another clients convert it again to ArraySegment<byte>.

can you help me?

**Comment by hdev72** [comment]
more simply how can i transport voice packet with websocket ? eg transport it in node

**Comment by martindevans** [comment]
Unfortunately you can't really use a websocket for Dissonance. VoIP requires Unreliable+Unordered packets (e.g. UDP) for good quality, but websocket is Reliable+Ordered (like TCP).

What are you trying to achieve that requires a websocket?

**Comment by hdev72** [comment]
Dear Admin, I've had so many problems with voice chat that I'm satisfied with average quality, I'm using Colyseus (tcp connection) for a party game, is it possible to transport voice packets or better way?  

On the other hand, I'm not very familiar with Mirror and... and I can't understand the server side, apparently every networks is peer2peer or some client should play server role , I didn't see any instructions about setting up the server in dissonance docs.

Thank you so much for your helps.
❤️❤️❤️❤️❤️

**Comment by hdev72** [comment]
> Dear Admin, I've had so many problems with voice chat before getting to know dissonance, that I'm satisfied with average quality, I'm using Colyseus (tcp connection) for a party game, is it possible to transport voice packets? What is your offer for better way?
> 
> On the other hand, I'm not very familiar with Mirror and... and I can't understand the server side, apparently every networks is peer2peer or some client should play server role , I didn't see any instructions about setting up the server in dissonance docs.
> 
> in my test im getting this error when receive packet: Client received packet 'HandshakeRequest'. This should only ever be received by the server
> 
> Thank you so much for your helps. ❤️

...

**Comment by martindevans** [comment]
I'm not familiar with "Colyseus", but if it is TCP only then unfortunately it is not suitable for voice chat. You will need to use a network system that supports Unreliable+Unordered packets for high quality voice.

However you don't need to move your entire game to another networ system! For example you could set up a server using one of our entwork integrations (DarkRift2 is probably the easiest to use as a standalone non-Unity server) just for voice chat. If you do that you don't need to write a custom networking code to integrate Dissonance with a new network system and you don't need to rewrite your game to use a new network system.

---

> apparently every networks is peer2peer

This is an optional thing, our base networking classes support either **client/server** (all voice packets go via the server) or **peer to peer** (there is a "master peer" to organise the session, but voice packets are sent directly to listeners).

> or some client should play server role

Every network system we support has some kind of master node which organises the chat session. In some networks (e.g. Mirror, DarkRift2) all voice traffic is sent via the server. In other networks (e.g. WebRTC, PUN2) voice traffic is sent directly from speakers to listeners.

> I didn't see any instructions about setting up the server in dissonance docs.

This depends completely on which network integration you want to use since our server code is just a set of scripts which you can run inside a Unity scene. The exception to this is DarkRift2, which supports running the server in a standalone non-Unity server process.

> Client received packet 'HandshakeRequest'. This should only ever be received by the server

Is this from a custom network integration you wrote, or from one of the free ones we have on the asset store?

**Comment by hdev72** [comment]
Is this from a custom network integration you wrote, or from one of the free ones we have on the asset store? 

Its a custom networking with colyseus (websocket tcp)

**Comment by hdev72** [comment]
Dear manager
Is DarkRift2 strong in ccu? The number of active users of our game will reach more than 5000 people in the future

**Comment by hdev72** [comment]
i have another question, when client connects to darkrift2 server should join to a room in darkrift2 server? or only should connect and set room for player in dissonance in client side?
i want dont be misstake , and all players only send and receive data in current joined dissonance room, not send global for all connected players to darkrift2

**Comment by martindevans** [comment]
> Its a custom networking with colyseus (websocket tcp)

In that case the `Client received packet 'HandshakeRequest'. This should only ever be received by the server` error indicates a bug in your custom network implementation. A client has sent a packet to the server, but you've delivered the packet to another client which causes this error.

> Simply how can i receive self packet and run it? For ex: hearing my voice from self speaker, If this is possible i can send and receive voice packets with my own networking very easily.

I'm not quite sure what you're asking, sorry.

> Is DarkRift2 strong in ccu? The number of active users of our game will reach more than 5000 people in the future

I'm not sure what the limits of DR2 are, best to ask on their Discord for more information. I would guess that 5000 CCU is probably too much for a single network session though. Can this be split into smaller sessions? e.g. a huge game like World Of Warcraft might have 5000 players in theory, but of course in practice they're in much smaller groups - e.g. a party of 5-10, a raid of 20-40, a city of ~100, all of these are much more manageable numbers!

> i have another question, when client connects to darkrift2 server should join to a room in darkrift2 server? or only should connect and set room for player in dissonance in client side?

Dissonance has it's own room system, I believe the way it works in DR2 is that a single "room" in DR2 is a "session" in Dissonance. i.e. it's only possible to talk to people within one single DR2 room, but you can have multiple Dissonance rooms within that.

That was a confusing explanation, so here's an example: If you were running league of legends you would create one DR2 Room for each game (with 10 players in the room). In Dissonance you would see those 10 players in the session. In Dissonance you would create 3 more rooms - TeamChatA, TeamChatB and GlobalChat.

**Comment by hdev72** [comment]
> In that case the Client received packet 'HandshakeRequest'. This should only ever be received by the server error indicates a bug in your custom network implementation. A client has sent a packet to the server, but you've delivered the packet to another client which causes this error.

I want to manage everything by myself, I just want Dissonance to give me the user's voice in the form of an packet and I can transport it in my own way then receive and play it to other users, is this possible in Dissonance?

That is, I want only the operation of capturing and converting to packets on the sender's side, and the operation of accepting the packet and broadcasting on the receiver's side from Dissonance.

**Comment by hdev72** [comment]
thank you so much, offline mode helped me.

**Comment by martindevans** [comment]
Looks like we both posted message at exactly the same time! I'm glad offline mode is what you were looking for :)

**Comment by hdev72** [comment]
yes in the same time :)

**Comment by hdev72** [comment]
Please completely delete this issue.
I had asked misleading questions that confuse users.
