### ISSUE TITLE
[Feature] TNet 3 Support

### ISSUE THREAD

**Issue by TorbjornKett** [Placeholder-Software/Dissonance#26]
## Context
Implementation of TNet 3 integration request

**Comment by fingerx** [comment]
@martindevans  Any News?

**Comment by martindevans** [comment]
Some progress on this. Someone else raised this issue on Discord with Aren (the TNet developer) and he's interested in collaborating on an integration. I'm going to be investigating it this week or next week!

**Comment by martindevans** [comment]
It's finally released! The Dissonance+TNet3 integration is available on the asset store [here](https://assetstore.unity.com/packages/tools/integration/dissonance-for-tnet3-154374?aid=1100lJDF).
