### ISSUE TITLE
Can Add Option Extera Large item For Frame Size?

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#260]
hello dear admin
is there any way to save more cpu usage of server with add option extera large for frame size?

here is my example edit:

        private static readonly int[] PermittedFrameSizesSamples = {
            (int)(2.5f * FixedSampleRate / 1000),
            (int)(5 * FixedSampleRate / 1000),
            (int)(10 * FixedSampleRate / 1000),
            (int)(20 * FixedSampleRate / 1000),
            (int)(40 * FixedSampleRate / 1000),
            (int)(60 * FixedSampleRate / 1000),
            (int)(80* FixedSampleRate / 1000) // added by me
        };

my question is how much can we increase number in this array to save more cpu and keep audio quality acceptable? 

thnks

**Comment by martindevans** [comment]
60 milliseconds is the maximum frame size supported by the encoder, so you can't add any more items to this list. For real-time voice chat this is already fairly high - even for two people talking with zero network latency they will experience effectively 120ms latency!
