### ISSUE TITLE
Unknown message id, This can happen if no handler was registered for this message. NetworkServer: failed to unpack and invoke message

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#264]
hello dear friends
im getting this following error when client connecting to server:

stdout: Unknown message id: 8290 for connection: connection(1195026647). This can happen if no handler was registered for this message.

stdout: NetworkServer: failed to unpack and invoke message. Disconnecting 1195026647.

server forcing client to disconnect

i tested when DissonanceSetup gameObject is disable mirror connecting successfully, but when its enable im getting this error,
in another test i enabled DissonanceSetup object after connected successfully to mirror, and then again this error showing.

**Comment by hdev72** [comment]
getting error when MirrorIgnoranceCommsNetwork is enabled

**Comment by martindevans** [comment]
If you try running the Mirror+Dissonance demo scene (included in the integration folder) do you get this same error?

**Comment by hdev72** [comment]
In dissonance sample, everything works fine in the editor environment, when I build for Windows, they cannot be connected, either the host or the client.
But the build in an empty project where only dissonance and mirror are imported is fine.
I do the same thing in both projects and put the same scenes as your sample in the build.

**Comment by hdev72** [comment]
Let me explain better, an empty Unity project with only Mirror and Dissonance works fine. (server, host, client and build is fine)
And I transfer this scenes and objects to my project and this error is given only in the Android output, there is still no problem in the editor and it is possible to connect to the blank project.

**Comment by hdev72** [comment]
I think the error is related to something outside the scene, like Player settings or something like that. Are there any settings in these sections that need to be done?

**Comment by hdev72** [comment]
Oh Im using Obfuscator, I forgot that.
I'm getting old :))
But this thread can be useful for those who forgot like me
