### ISSUE TITLE
Can not Instantiate before the client joined/created a room. State: PeerCreated

### ISSUE THREAD

**Issue by shoukailiang** [Placeholder-Software/Dissonance#265]
When I open “PuN2 game world”, an error will appear. I don't know how to solve it.
![image](https://user-images.githubusercontent.com/24668909/184787471-ab1474b1-b655-434d-88b1-2fb5b1e3849f.png)

![image](https://user-images.githubusercontent.com/24668909/184787690-87c888e1-e9e1-4e62-a235-082d497e1539.png)

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: e.g. v8.2.1 _(check Assets/Dissonance/changelog)_

- **Unity version**: e.g. 2020.3.36 Personal _(check Help > About Unity)_

- **Editor Operating System and version**: e.g. Microsoft Windows 11 
- **photon** 2.4.1

**Comment by martindevans** [comment]
You're meant to open the `PUN2 Demo` scene instead of directly opening the `PUN2 GameWorld` - the demo scene sets up the network session. Since you've closed the issue I asusmed you already figured it out :)
