### ISSUE TITLE
how fix echo in android? any recomennded voiceSettings?

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#266]
Hello dear admins
I published my game with dissonance and the players get an echo when more than one player is talking.
I tried to fix it but I have some problems
When I set the Audio Duck Attenuation to -25 or less, the echo is correct but the speaker volume is very low and does not hear the partner's voice.
And if I set it to -10 - -15, the echo doesn't work.

do you allready tested for android devices? and have u a recommended settings for fixing sound echo's?

thnks :x

**Comment by hdev72** [comment]
resolved by docs

**Comment by InderChicmic** [comment]
I am unable to remove noise and echo, tried tweaking values a number of times. Can you please share me the settings you set for android @hdev72 ?

**Comment by martindevans** [comment]
Ideally you _do_ want to attach the `Dissonance Echo Cancellation` filter to the Master mixer (i.e. the very last mixer in the audio system, which _all_ other audio passes through).
