### ISSUE TITLE
[help] Positional Tracking Setup

### ISSUE THREAD

**Issue by methot-ilya-3ds** [Placeholder-Software/Dissonance#268]
## Context
Using Dissonance Mirror I've attempted to setup the positional audio using the [Positional Tracking Documentation](https://placeholder-software.co.uk/dissonance/docs/Tutorials/Position-Tracking.html#setup-tracking)

## Expected behaviour
I'd like all players to have positional tracking enabled so their voices emanate from their player model.

## Actual behaviour
All of my players have the Mirror Player component, however only the local player seems to have the positional tracking enabled.
![image](https://user-images.githubusercontent.com/64415447/186012494-6c7f7f0b-6b63-46a0-8aed-7b99d6731a07.png)

- **Dissonance version used**:

v8.1.0

- **Unity version**:

Unity 2021.3.5f1

**Comment by martindevans** [comment]
Could you post a screenshot of the inspector for a remote player and the DissonanceComms component when you're running the scene (make sure they're both taken from the same session, so the IDs are the same).

**Comment by methot-ilya-3ds** [comment]
So I think I needed to update the server build - which i've done. Both players are now reading as positional tracking, however the audio seems to be transmitting to the room rather than to the player, since the volume does not decrease as I manually move the speaking player away from the other player.

**Comment by martindevans** [comment]
When you send voice (to a room or to a player) you can choose if the voice is positional in the VoiceBroadcastTrigger by toggling [this option](https://placeholder-software.co.uk/dissonance/docs/Reference/Components/Voice-Broadcast-Trigger.html#use-positional-data). If you're sending through several channel at once voice will be non-positional if _any_ of them are non-positional.

Also make sure that the playback prefab you are using has a volume falloff curve that matches what you expect.

**Comment by methot-ilya-3ds** [comment]
First of all thank you for the help.

Secondly, I've enabled positional audio in the Dissonance Comms object and set the Dissonance Comms Playback Prefab. 

However, I don't seem to see the Playback Prefab being instantiated anywhere in the scene. I'm assuming that its supposed to be parented to the player objects as they join but this does not seem to be the case.

**Comment by methot-ilya-3ds** [comment]
Audio Source Prefab:
![image](https://user-images.githubusercontent.com/64415447/186025681-9d841357-48e9-4919-b834-00954ddc3305.png)
Dissonance Comms Prefab:
![image](https://user-images.githubusercontent.com/64415447/186025906-e00d7088-42ec-4621-a748-f62a6b4155ab.png)
Spawned Players:
![image](https://user-images.githubusercontent.com/64415447/186025945-17cba9c6-f69b-4fef-ae89-a4754bd9039d.png)
![image](https://user-images.githubusercontent.com/64415447/186026008-73923d5c-a8d3-470e-a1ac-f8d196b4aada.png)

**Comment by methot-ilya-3ds** [comment]
Got it working - I can see that the audio source was spawning within the Dissonance Audio object. Changing the 3D audio settings in that spawned Audio Source did the trick!
