### ISSUE TITLE
linux connection limit ( socket connection refused)

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#274]
hello dear friends
im getting an error like this : socket connection refused when my mirror server instances getting more than 250 instances on linux server
i want to ask you what is configurations i should change and increase?

**Comment by martindevans** [comment]
hi hdev72. a "Connection Refused" message is a Mirror issue, not Dissonance. I recommend asking on their Discord server for help: https://discord.gg/8pmJkfH
