### ISSUE TITLE
[BUG] ISO Crash on iPreprocessingPipeline.Start();

### ISSUE THREAD

**Issue by andyspeak1993** [Placeholder-Software/Dissonance#282]
crash after calling iPreprocessingPipeline.Start(); on IOS

short-term fix dont call PreprocessingPipeline.Start();

[Dissonance:Core] (15:55:36.442) AudioPluginDissonanceNative: Rnnoise is not supported on this platform
Dissonance.Logs:SendLogMessage(String, LogLevel)
Dissonance.Log:WriteLog(LogLevel, String)
Dissonance.Audio.Capture.AudioPluginDissonanceNative:Dissonance_CreateRnnoiseState()
Dissonance.Audio.Capture.RnnoisePreprocessor:set_Enabled(Boolean)
Dissonance.Audio.Capture.RnnoisePreprocessor:.ctor()
Dissonance.Audio.Capture.WebRtcPreprocessingPipeline:ThreadStart()
Dissonance.Audio.Capture.BasePreprocessingPipeline:ThreadEntry()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)

**Comment by martindevans** [comment]
The message "Rnnoise is not supported on this platform" is just a warning, it shouldn't cause any further issues. See `Assets/Plugins/Dissonance/Core/Audio/Capture/AudioPluginDissonanceNative.cs` line 30:

```csharp
if (!_rnnoiseWarning)
{
    Log.Warn("Rnnoise is not supported on this platform");
    _rnnoiseWarning = true;
}
```

Do you have any details about the crash?

**Comment by martindevans** [comment]
I'm going to close for now. Please open a new issue and properly fill in the issue template, it includes a lot of details that I need to know to try and diagnose your issue.
