### ISSUE TITLE
[bug] IOS crash on start Post processing

### ISSUE THREAD

**Issue by andyspeak1993** [Placeholder-Software/Dissonance#283]
## Context
crash when triggering post-processing 

## Expected behaviour
not to crash

## Actual behaviour
crashing

## Workaround
don't use post-processing

## Fix
_Not obligatory! If you think you know exactly how this problem should be fixed tell us how_

## Steps to Reproduce
1. create new unity project
2. import dissonance
3. build for ios with a dissonance demo scene as main scene
4. launch app wait for crash

## Your Environment
unity 2022.3.11
Dissonance version 9.04

##Xcode log output
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
[Dissonance:Recording] (11:39:23.974) BasicMicrophoneCapture: Began mic capture (SampleRate:48000Hz, FrameSize:960, Buffer Limit:2^13, Latency:20ms, Device:'iPhone audio input')
Dissonance.Logs:SendLogMessage(String, LogLevel)
Dissonance.Log:WriteLog(LogLevel, String)
Dissonance.Log:WriteLogFormat(LogLevel, String, TA, TB, TC, TD, TE)
Dissonance.Audio.Capture.BasicMicrophoneCapture:StartCapture(String)

[Dissonance:Core] (11:39:23.977) AudioPluginDissonanceNative: Rnnoise is not supported on this platform
Dissonance.Logs:SendLogMessage(String, LogLevel)
Dissonance.Log:WriteLog(LogLevel, String)
Dissonance.Audio.Capture.AudioPluginDissonanceNative:Dissonance_CreateRnnoiseState()
Dissonance.Audio.Capture.RnnoisePreprocessor:set_Enabled(Boolean)
Dissonance.Audio.Capture.RnnoisePreprocessor:.ctor()
Dissonance.Audio.Capture.WebRtcPreprocessingPipeline:ThreadStart()
Dissonance.Audio.Capture.BasePreprocessingPipeline:ThreadEntry()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)

Audio effect Dissonance Echo Cancellation could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.

**Comment by andyspeak1993** [comment]
issue happened in project and was able to repo in a empty project with the demo scene Offline Demo Scene

**Comment by andyspeak1993** [comment]
enabling dissonance full logs didnt produce anymore data

**Comment by andyspeak1993** [comment]
any update for the above? was you able to repo the issue

**Comment by martindevans** [comment]
Sorry I haven't been able to reproduce it. I don't have an iPhone available to test with at the moment. Can you send me whatever logs you do have and I'll try to work with that?

**Comment by andyspeak1993** [comment]
managed to resolve the issue in the end. issue was dissonance and another package had conflicting post requirements. deleting one or the other fixes the issue.

**Comment by martindevans** [comment]
Glad to hear you worked it out! What was the other asset?
