### ISSUE TITLE
Unity 2019.4 + Dissonance 9.0.4 Old .Net Constructions Support Patch

### ISSUE THREAD

**Issue by DevsDaddy** [Placeholder-Software/Dissonance#285]
**Dissonance 9.0.4 Doesn't support Unity 2019.4.***
This version of Dissonance utilizes new .Net functionality not available in Unity 2019.4.*.

**Example of not supported code in Unity 2019.4**
```
equality ??= EqualityComparer<T>.Default;
```

**Attached is a patch to fix all unsupported .Net constructions:**
[0001-Dissonance-Unity-2019-Support.patch](https://github.com/Placeholder-Software/Dissonance/files/14692888/0001-Dissonance-Unity-2019-Support.patch)

**Comment by martindevans** [comment]
Not supporting 2019.4 is a deliberate choice - Dissonance only supports the versions of Unity which are supported by Unity themselves. Per [this page](https://unity.com/releases/editor/qa/lts-releases), that's currently 2021.3:

> Unity 2021.3 is now the legacy LTS. It will be updated monthly until it reaches the end of its support cycle in mid-2024.

Thank you for the patch though. If anyone else asks about porting Dissonance back to 2019.4 I can direct them here.
