### ISSUE TITLE
EventQueue: Exception invoking event handler

### ISSUE THREAD

**Issue by artemiys930519** [Placeholder-Software/Dissonance#289]
Dissonance cannot send audio from the microphone. The person speaking is constantly disconnected and re-established.

On Scene exist:
- DissonanceComms,
- MirrorIgnoranceCommsNetwork,
- Voice Broadcast Trigger - Global Room
- Voice ReceiptTrigger -Global Room

Unity - 2021.3.35f
Mirror - version 89.0.0 (LatensySimulation->KCP Transport)
Dissonance - version 9.0.4
Client-  Android and PC
Server - linux(but error exist in editor too)

Error StackTrace
[Dissonance:Network] (08:49:07.443) EventQueue: Exception invoking event handler: System.NullReferenceException: Object reference not set to an instance of an object
  at Services.AudioService.DissonanceAudioService.OnPlayerStartSpeakingHandler (Dissonance.VoicePlayerState playerState) [0x00001] in Assets\Voice\Scripts\Services\AudioService\Dissonance\DissonanceAudioService.cs:104 
  at Dissonance.DissonanceComms.Net_PlayerStartedSpeaking (System.String player) [0x00039] in \Assets\Plugins\Dissonance\Core\DissonanceCommsImpl.cs:524 
  at Dissonance.Networking.BaseCommsNetwork`5[TServer,TClient,TPeer,TClientParam,TServerParam].OnPlayerStartedSpeaking (System.String obj) [0x00001] in Assets\Plugins\Dissonance\Core\Networking\BaseCommsNetwork.cs:526 
  at Dissonance.Networking.Client.EventQueue.InvokeEvent[T] (T arg, System.Action`1[T] handler) [0x00002] in l\Assets\Plugins\Dissonance\Core\Networking\Client\EventQueue.cs:296 
UnityEngine.Debug:LogError (object)
Dissonance.Logs/LogMessage:Log () (at Assets/Plugins/Dissonance/Core/Log.cs:70)
Dissonance.Logs:SendLogMessage (string,Dissonance.LogLevel) (at Assets/Plugins/Dissonance/Core/Log.cs:97)
Dissonance.Log:WriteLog (Dissonance.LogLevel,string) (at Assets/Plugins/Dissonance/Core/Log.cs:170)
Dissonance.Log:WriteLogFormat<System.Exception> (Dissonance.LogLevel,string,System.Exception) (at Assets/Plugins/Dissonance/Core/Log.cs:179)
Dissonance.Log:Error<System.Exception> (string,System.Exception) (at Assets/Plugins/Dissonance/Core/Log.cs:420)
Dissonance.Networking.Client.EventQueue:InvokeEvent<string> (string,System.Action`1<string>) (at Assets/Plugins/Dissonance/Core/Networking/Client/EventQueue.cs:300)
Dissonance.Networking.Client.EventQueue:DispatchEvents (System.Nullable`1<System.DateTime>) (at Assets/Plugins/Dissonance/Core/Networking/Client/EventQueue.cs:210)
Dissonance.Networking.BaseClient`3<Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceServer, Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceClient, Dissonance.Integrations.MirrorIgnorance.MirrorConn>:RunUpdate (System.DateTime) (at Assets/Plugins/Dissonance/Core/Networking/BaseClient.cs:207)
Dissonance.Networking.BaseClient`3<Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceServer, Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceClient, Dissonance.Integrations.MirrorIgnorance.MirrorConn>:Update () (at Assets/Plugins/Dissonance/Core/Networking/BaseClient.cs:169)
Dissonance.Networking.BaseCommsNetwork`5/Session<Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceServer, Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceClient, Dissonance.Integrations.MirrorIgnorance.MirrorConn, Dissonance.Unit, Dissonance.Unit>:Update () (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:158)
Dissonance.Networking.BaseCommsNetwork`5<Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceServer, Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceClient, Dissonance.Integrations.MirrorIgnorance.MirrorConn, Dissonance.Unit, Dissonance.Unit>:Update () (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:332)
Dissonance.Integrations.MirrorIgnorance.MirrorIgnoranceCommsNetwork:Update () (at Assets/Dissonance/Integrations/MirrorIgnorance/MirrorIgnoranceCommsNetwork.cs:82)

Detail information about error
Error: Attempted to access as TextMessage, but type is PlayerExitedRoom! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: EA60F116-8B43-49B9-8625-2E19CF5137BD

**Comment by artemiys930519** [comment]
If need more information
![image](https://github.com/Placeholder-Software/Dissonance/assets/12072497/f2b8afcf-bfee-403b-9acf-f085c5f9ec13)

**Comment by martindevans** [comment]
@artemiys930519 the code at the top of the stack trace is `Services.AudioService.DissonanceAudioService.OnPlayerStartSpeakingHandler`, I assume this is a script of yours? If so, could you show me the code for that? Thanks.

**Comment by artemiys930519** [comment]
the method displays a log at the moment the user starts talking
![image](https://github.com/Placeholder-Software/Dissonance/assets/12072497/31f10236-d8a2-413b-8113-5f68a0ef8840)

**Comment by martindevans** [comment]
Could you modify that code to handle `playerState.Tracker` being null. That's allowed to be null if tracking is not set up, or if it has not yet initialised for this player. That may be the cause of the issue.

**Comment by artemiys930519** [comment]
Yes, that helped thanks
