### ISSUE TITLE
A worrisome warning

### ISSUE THREAD

**Issue by morderkaine1** [Placeholder-Software/Dissonance#29]
A warning that pops up a lot as things are working. Just seems to be a common warning.

[Dissonance:Playback] EncodedAudioBuffer: Error: Encoded audio heap is getting very large (43 items)! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: 59EE0102-FF75-467A-A50D-00BF670E9B8C
UnityEngine.Debug:LogWarning(Object)
Dissonance.LogMessage:Log() (at Assets/Plugins/Dissonance/Core/Log.cs:91)
Dissonance.Logs:WriteMultithreadedLogs() (at Assets/Plugins/Dissonance/Core/Log.cs:105)
Dissonance.DissonanceComms:Update() (at Assets/Plugins/Dissonance/DissonanceComms.cs:491)

**Comment by martindevans** [comment]
Hi morderkaine1,

This is the same issue as you reported in #28 (the two messages are different ways of detecting the same situation). I'll close this issue and we can track it over in the other one :)
