### ISSUE TITLE
older version for photon fusion 1 and not 2

### ISSUE THREAD

**Issue by amanmamgain9** [Placeholder-Software/Dissonance#294]
Hey where to got the older version for photon fusion 1 and not 2

**Comment by amanmamgain9** [comment]
recently purchased the dissonace for unity but cant integrate it into my game

**Comment by martindevans** [comment]
We dropped support for Fusion 1.0 and upgraded the package to Fusion 2.0 recently. If you like I can dig a copy of the older Fusion 1.0 package out from git history and send that to you? If so, please contact me by email (martin@placeholder-software.co.uk) or [Discord](https://discord.gg/E4uGzqddjz) with your invoice number and I'll send that back to you.

**Comment by amanmamgain9** [comment]
cool...have dmed you on discord
