### ISSUE TITLE
Incorrect port number in the LLAPI Quick Start document.

### ISSUE THREAD

**Issue by erobledo** [Placeholder-Software/Dissonance#31]
The document specifies that the default port is 5589. The actual value is 5889 (UNetCommsNetwork.cs:32).

https://github.com/Placeholder-Software/Dissonance/blob/master/docs/Basics/Quick-Start-UNet-LLAPI.md

**Comment by martindevans** [comment]
Well spotted and thanks for the report. I've just pushed up a fix for that :)
