### ISSUE TITLE
[help] If host/server disconnects can host be transferred?

### ISSUE THREAD

**Issue by sayangel** [Placeholder-Software/Dissonance#35]
If the host disconnects should InitializeAsServer() be called on another one of the remaining peers to ensure that dissonance continues working as expected?

**Comment by martindevans** [comment]
Hi sayangel,

Unfortunately that won't work.

Dissonance components cannot be used in multiple sessions (each time you call InitializeAsX you're starting a new session). You need to tear down and recreate _all_ the Dissonance components - this include the broadcast and receipt triggers. Once that's done the normal setup flow applies; call InitializeAsServer on the appropriate peer and InitializeAsClient on all the others.

We realise this isn't a great way to handle this and hope to fix it soon! _Probably_ by implementing automatic host migration for all integrations where that makes sense so you don't even need to think about this.

**Comment by haydenjameslee** [comment]
+1 for auto host migration

**Comment by haydenjameslee** [comment]
I solved this by instantiating and deleting the dissonance prefab whenever the "server" changes.

**Comment by martindevans** [comment]
That should work, just make sure you delete *all* Dissonance related components. The triggers internally keep a reference to the DissonanceComms component, so you need to make sure they're recreated too.

We're going to have a much better experience for this in the next patch (we're adding the finishing touches today, should be available on the store in about a week). The network system will detect when it loses connection and shut itself down and then it will try to reconnect when it can (i.e. basic host migration should work).

**Comment by haydenjameslee** [comment]
Great! Looking forward to it.

**Comment by martindevans** [comment]
This feature is now available on the store with Dissonance 2.0.0 so I'll close this issue.
