### ISSUE TITLE
photon integration issue with version 2

### ISSUE THREAD

**Issue by Asaadmk** [Placeholder-Software/Dissonance#40]
[bug]

Assets/Dissonance/Integrations/PhotonUnityNetworking/PhotonCommsNetwork.cs(28,41): error CS0115: `Dissonance.Integrations.PhotonUnityNetworking.PhotonCommsNetwork.CreateServer()' is marked as an override but no suitable method found to override

Assets/Dissonance/Integrations/PhotonUnityNetworking/PhotonCommsNetwork.cs(10,11): error CS0305: Using the generic type `Dissonance.Networking.BaseCommsNetwork<TServer,TClient,TPeer,TClientParam,TServerParam>' requires `5' type argument(s)

Assets/Dissonance/Integrations/PhotonUnityNetworking/PhotonCommsNetwork.cs(32,33): error CS0115: `Dissonance.Integrations.PhotonUnityNetworking.PhotonCommsNetwork.Shutdown()' is marked as an override but no suitable method found to override

**Comment by TomGillen** [comment]
You will need to install the latest version of the Photon integration, as 2.0.0 introduced some breaking changes to the network code.

You can find the download page from within Unity via Window -> Dissonance -> Welcome Screen, and clicking Open Integrations List.

**Comment by Asaadmk** [comment]
yes, sorry i just rushed in putting the issue without looking into it.
