### ISSUE TITLE
[Help] Unplugging Headphones Breaks Audio

### ISSUE THREAD

**Issue by sayangel** [Placeholder-Software/Dissonance#41]
When in a session if I unplug/plug headphones the audio isn't gracefully transferred to the headphones. Is there an issue switching audio source?

**Comment by martindevans** [comment]
Hi sayangel,

Is this a problem with audio *playback* not transferring to the headphones, or with audio *capture* not transferring to a headset with a mic?

**Comment by martindevans** [comment]
Oops, this was auto closed by Github because it was mentioned in an internal PR which was just merged. Sorry about that.

We've just merged a fix for #33, which this issue *might* be a duplicate of.

**Comment by martindevans** [comment]
I've just closed issue #33 with a fix released to the asset store. I think this was probably a duplicate of that so I'll close it - if the issue persists please feel free to continue posting in this thread and I'll reopen it :)
