### ISSUE TITLE
HlApiPlayerTracker missing in NetworkManager spawnable prefabs

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#5]
Small thing but in the Unet_HLAPI I think the NetworkManager doesn't have 'HLApiPlayerTracker' as spawnable prefab and it triggers an error when a client connects.

**Comment by martindevans** [comment]
That's actually really important for the correct functioning of the HLAPI integration!

**Comment by martindevans** [comment]
I can't reproduced this :(

I just imported the Dissonance_0.0.1 package into a totally new project, ran the HlapiDemoScene and connected a second client. As you can see, I get no errors (and the HLAPI tracker object has successfully been created):

![2clients](https://cloud.githubusercontent.com/assets/177519/19558282/83b0a78e-96c1-11e6-9342-32f49d2f6fa0.png)

When you imported Dissonance are you certain you had the prefab selected?

![import](https://cloud.githubusercontent.com/assets/177519/19558313/b0276988-96c1-11e6-9de1-9c39adb019af.png)

**Comment by citron4000** [comment]
That was a problem on my side then, thanks for looking into it and sorry about that.
