### ISSUE TITLE
[bug] Can't drag HlapiPlayerTracker prefab to Registered Spawnable Prefabs list

### ISSUE THREAD

**Issue by jakemoves** [Placeholder-Software/Dissonance#52]
## Context
Following the [Unity HLAPI QuickStart guide](http://dissonance.readthedocs.io/en/latest/Basics/Quick-Start-UNet-HLAPI/#step-1-dissonance-comms-object), in step 1a, I am at the step of adding the HlapiPlayerTracker to the Registered Spawnable Prefabs list.

## Expected Behavior
Whether dragging or using the picker, I expect to be able to add the prefab to the list.

## Actual Behavior
The list refuses to accept the prefab. I notice that the tooltip on the Registered Spawnable Prefabs list says that prefabs must have a Network Identity component. I also notice that the HlapiPlayerTracker does not have that component...

## Workaround
If I add a Network Identity component to the prefab, then I can drag it onto the Registered Spawnable Prefabs list. I can then remove the Network Identity component and everything works correctly (I can carry on through the rest of the guide successfully).

## Your Environment

- **Dissonance version used**: 3.0.0 (as per changelog.txt)

- **Unity version**: 5.5p1, 2017.1

- **Editor Operating System and version**: macOS Sierra

**Comment by martindevans** [comment]
Hi jakemoves,

Looks like the documentation is slightly out of date - as of Dissonance 3.0.0 the prefab is no longer required. I'll rewrite that section tomorrow :)

**Comment by jakemoves** [comment]
Awesome! I am otherwise thrilled with the product, I was able to get both desktop and iOS proofs of concept up and running in just a few hours. (Incidentally, basic functionality seems fine on the iOS 11 beta.)

**Comment by martindevans** [comment]
I've just rewritten that section of the docs (and some other bits of the documentation which weren't quite up to date with the changes in 3.0.0) so I'll close this issue now. If you're happy with how this issue was handled please consider rating and reviewing us on the [asset store](https://www.assetstore.unity3d.com/en/#!/content/70078) :)
