### ISSUE TITLE
Voice Settings Documentation WAAAAAAY out of date.

### ISSUE THREAD

**Issue by LordSkittles** [Placeholder-Software/Dissonance#53]
The documentation for the Voice Settings asset editor is at least 10 months out of date, if you could please document the new layout of the editor to make it more clear what the different levels of Voice Suppression actually do.

**Comment by martindevans** [comment]
Wow you're right that page is _ancient_. I'll rewrite it right now :)

**Comment by martindevans** [comment]
The [VoiceSettings documentation](https://dissonance.readthedocs.io/en/latest/Reference/Audio/VoiceSettings/) has been rewritten.
