### ISSUE TITLE
[Bug] HlapiServer: Received a packet with incorrect session ID log spew doesn't recover

### ISSUE THREAD

**Issue by GabeBigBoxVR** [Placeholder-Software/Dissonance#59]
## Context
HLAPI server repeatedly spews this logline on every frame when a client disconnects.

[Dissonance:Network] HlapiServer: Received a packet with incorrect session ID. Expected 372436445, got 1790607069. Resetting client.

## Expected Behavior
Should not log spew and correctly reset the client.

## Actual Behavior
Log spew on server

## Steps to Reproduce
A client disconnects or from an HLAPI server

## Your Environment
- Dissonance 3.0.2
- Unity 2017.1.1p2
- Windows 10 64-bit
- Windows, x86_64, Release

**Comment by martindevans** [comment]
Are you re-using Dissonance components between network sessions? If so I suspect I already caught this bug and have an open pull request to merge it into the dev branch - any extra details you can work will help me confirm that though.

**Comment by GabeBigBoxVR** [comment]
Yes, sometimes we do reuse them between sessions.
But in this case, it’s just a client that disconnected.

**Comment by martindevans** [comment]
When the client reconnects (after printing the message) do you see another message a bit further down the log showing:

 > Received handshake response from server, joined session '???????'

If so, is it the "expected" value referenced in the first message? When the server boots up you should see a message:

> Constructing host. SessionId:??????

What's the session ID reference in that message?

**Comment by GabeBigBoxVR** [comment]
No, we don't ever see that message. The message "[Dissonance:Network] HlapiServer: Received a packet with incorrect session ID. Expected 372436445, got 1790607069. Resetting client." is just logged every frame.

**Comment by martindevans** [comment]
What is your log level in Dissonance? You can check in `Window > Dissonance > Diagnostic Settings`.
 - The `Constructing host. SessionId:????` is shown at Network:Info level (or higher) on the _server_ instance.
 - The `Received handshake response from server, joined session '{0}'` is shown at Network:Info level (or higher) on the _client_ instance.

> The message below is logged every frame.

Do the numbers change some/every when it is logged?

**Comment by GabeBigBoxVR** [comment]
Our log level is Info for Core, Recording, Network and Playback.
No, the numbers do not change across any other frames.

**Comment by martindevans** [comment]
I think that we've already caught this issue in testing and have a fix for the next version. We're putting together the final version right now to submit to the store tomorrow, it should be available within the week. If you [contact me](mailto://martin@placeholder-software.co.uk) with your Order number I can send you a copy of that as soon as we submit it to the store so you don't have to wait.

**Comment by martindevans** [comment]
[Dissonance 3.0.3](https://placeholder-software.co.uk/dissonance/releases/3.0.3.html) just went live on the asset store with the fixes I sent you by email merged in. I'll close this issue now, feel free to re-open it if this continues to be a problem.
