### ISSUE TITLE
Buid error for UWP (Hololens)

### ISSUE THREAD

**Issue by awonnink** [Placeholder-Software/Dissonance#61]
Hi,
I get a error when trying to build for UWP (HoloLens D3D) on saying 'CS0117: 'Math' does not contain a definition for 'DivRem''. It is used in the PacketLossMonitor.

I am working with Dissonance 3.0.2 now, and this compiles correctly for PC.
The Unity version is 2017.1.1f1, My system Windows 10 x64

I guess the solution is just to add your own DivRem function (after commenting the relevant lines out, it compiles ok)

Albert Jan

**Comment by martindevans** [comment]
That's an odd thing to be missing! As you suggest we'll just have to write our own DivRem. We're doing the last work for the next release today, so we *might* squeeze that in at the last minute.

**Comment by TomGillen** [comment]
We have just merged in a small fix for this in our internal builds. If you want to make the change yourself rather than wait for a new release, then replace the line calling `DivRem` with:

```c#
var midIndex = (int) Math.Ceiling((_tmpLossValues.Count - 1) / 2.0f);
```

**Comment by awonnink** [comment]
Great, thank you both!

**Comment by martindevans** [comment]
[Dissonance 3.0.3](https://placeholder-software.co.uk/dissonance/releases/3.0.3.html) just went live on the asset store with this fix merged in. I'll close this issue now, feel free to re-open it if this continues to be a problem.
