### ISSUE TITLE
Issue switching "Photon Rooms" using PhotonNetwork

### ISSUE THREAD

**Issue by maburkitt** [Placeholder-Software/Dissonance#62]
## Context
There is a problem when leaving a room and joining a new room using the photon engine. This is the actual "PhotonRoom" not a Dissonance voice room.

## Expected Behavior
When leaving a room and joining a new room, the dissonance engine should handle the transition based on the photon events, and the user should be able to talk to and head the people in the new room

## Actual Behavior
After the room is changed, large numbers of error messages are generated:

PhotonClient: Received a packet with incorrect session ID
 PhotonClient: Kicked from session - wrong session ID

From the message trace, it appears dissonance is disconnecting itself when the user leaves a room, and then re-initialising, but looks like the session id is not being updated?

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. Setup dissonance as described in the tutorial
2. Initialise the scene
3. Disconnect from the room (using LeaveRoom()) and then reconnect to the new room (JoinOrCreateRoom("NewRoomName"))
4. Errors appear in the console

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: # 3.0.2

- **Unity version**: 2017.2.0f3

- **Editor Operating System and version**: e.g. Microsoft Windows 10 Pro 10.0.10586 (x64)

**Comment by martindevans** [comment]
Hi maburkitt,

I fixed a couple of issues related to session numbers last release (e.g. #59) - could I get you to upgrade to Dissonance 3.0.3 to see if that fixes the problem.

**Comment by maburkitt** [comment]
Sorry, hadn't noticed the new version. Yes, this appears to have solved the problem.

I have closed the issue

thanks!

Mark
