### ISSUE TITLE
Acoustic Echo Cancellation Doc Pic Not Found

### ISSUE THREAD

**Issue by fingerx** [Placeholder-Software/Dissonance#72]
Acoustic Echo Cancellation Doc Pic Not Found

**Comment by martindevans** [comment]
Unfortunately that's expected when viewing the draft. The paths on the [live docs site](https://dissonance.readthedocs.io/en/latest/) are different to how they are on Github. You can find all the relevant images [here](https://github.com/Placeholder-Software/Dissonance/pull/71/files#diff-989c9c12361de4c3982519de5f743f67).
