### ISSUE TITLE
[bug] `Mute` is not defined

### ISSUE THREAD

**Issue by Nagasaki45** [Placeholder-Software/Dissonance#82]
## Context

I'm trying to set the `Mute` field. My code looks like that:

```
comms = GameObject.FindGameObjectWithTag("DissonanceSetup").GetComponent<DissonanceComms>();
comms.Mute = true;
```

## Expected Behavior

To compile and mute the local player [as documented](https://dissonance.readthedocs.io/en/latest/Tutorials/Script-Controlled-Speech/).

## Actual Behavior

Compilation error:

```
Type `Dissonance.DissonanceComms' does not contain a definition for `Mute' and no extension method `Mute` of type `Dissonance.DissonanceComms` could be found. Are you missing an assembly reference?
```

## Your Environment

- **Dissonance version used**: 6.0.2
- **Unity version**: 2017.3.0p2 Personal (64Bit)
- **Editor Operating System and version**: Microsoft Windows 10 Home 1709
- I'm working with HLAPI.

**Comment by martindevans** [comment]
Hi Nagasaki45,

Sorry about that, it looks like that's been incorrect in the documentation for very long time. It should be `IsMuted`.

**Comment by Nagasaki45** [comment]
Thanks for the super quick response!

BTW, why not to keep the issue open to make sure someone updates the docs?

**Comment by martindevans** [comment]
> why not to keep the issue open to make sure someone updates the docs?

I already updated them. You may need to clear the cache to see the latest docs :)

**Comment by Nagasaki45** [comment]
Amazing support! Thank you very very much.
