### ISSUE TITLE
Voice Chat not working on server

### ISSUE THREAD

**Issue by donnytrona** [Placeholder-Software/Dissonance#85]
## Context
Been trying to run an upgraded version of Dissonance on the Server but doesn't seem to work. Locally works just fine, but once the server addresses changes from 127.0.0.1 to our address is stop workings. We tried to install everything fresh and just run the BOLT demo but no luck. Voice only stops working when we take the server off local and to live.

[Dissonance:Network] (22:46:36.621) VoiceSender`1: Attempted to send voice before assigned a client ID by the host (100 packets discarded so far)
UnityEngine.Debug:LogWarning(Object)
Dissonance.LogMessage:Log() (at Assets/Plugins/Dissonance/Core/Log.cs:99)
Dissonance.Logs:WriteMultithreadedLogs() (at Assets/Plugins/Dissonance/Core/Log.cs:120)
Dissonance.Editor.Windows.Startup:Update() (at Assets/Plugins/Dissonance/Editor/Windows/Startup.cs:35)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: v6.1.0

- **Unity version**: 2017.3.0f3

- **Editor Operating System and version**: Windows Server 2016 Standard

- **Build Settings**: Windows

**Comment by martindevans** [comment]
Hi donnytrona, is this a regression in 6.1.0 i.e. did it work in an earlier version of Dissonance? Are you certain that the client and the server are using the same version of Dissonance? Are non-Dissonance BOLT network packets getting through ok? 

Could you turn up the logging settings in `Window > Dissonance > Diagnostic Settings` to:

 - Core:Trace
 - Recording:Debug
 - Network:Trace
 - Playback:Debug

And send me a log from the client and the server (ideally from the same session).

**Comment by donnytrona** [comment]
Server:
[Server -output_log.txt](https://github.com/Placeholder-Software/Dissonance/files/1849975/Server.-output_log.txt)

Client - Though Editor
[Editor.log](https://github.com/Placeholder-Software/Dissonance/files/1849978/Editor.log)

Thank you for the quick reply. We had v5.0.0 running on the server which was working, but been trying to upgrade and running into this problem. Client and Server are both using the same version and Non-dissonance Bolt network packets are getting through ok.

**Comment by martindevans** [comment]
Luckily the problem was quite easy to spot. The server log contains this:

> Plugins: Failed to load 'C:/Users/Administrator/Desktop/VoilaRelease/VoilaRelease_Data/Plugins/opus.dll' with error 'The specified module could not be found.'.

This exception causes Dissonance not to load at all on your server (hence no Dissonance packets ever get replied to, because the server is dead). My best guess would be that you don't have the correct dependencies installed on the server - check out the documentation on runtime dependencies [here](https://dissonance.readthedocs.io/en/latest/Basics/End-User-Requirements/).

**Comment by donnytrona** [comment]
Alright cool thanks for all your help.
