### ISSUE TITLE
Client Disconnect Error

### ISSUE THREAD

**Issue by cborg15** [Placeholder-Software/Dissonance#89]
## Context
Receive an error stating, "ServerDisconnected due to error: Timeout" whenever a client leaves the room.

## Expected Behavior
The program shouldn't crash. Player should disconnect without affecting others in the room.

## Actual Behavior
Program crashes and displays the error message stated above.

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. LAN Host a room on Unity Editor
2. LAN Client join from an .exe of the project build
3. Click "Stop" button on client side
4. Unity Editor Program crashes and error message is displayed in the console.

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: v 6.1.0 

- **Unity version**:  5.6.4f1 

- **Editor Operating System and version**: Microsoft Windows 10 Enterprise 10.0.16299 (x64) 

- **Build Settings**: 

- **Link to your project**:

**Comment by martindevans** [comment]
Which network integration are you using?

**Comment by cborg15** [comment]
UNet_HLAPI

**Comment by cborg15** [comment]
Extra bit of info: 

If I press the "Stop" button on the host in the Unity Editor, the console displays a warning log: 
          "Channels not initialized sending on id '0"

And is followed by an error log: HlapiServer: 
           "Failed to send reliable packet (unknown HLAPI error)"

**Comment by martindevans** [comment]
Looks like something is wrong with the HLAPI configuration. Did you make sure you did [step 1a of the setup](https://dissonance.readthedocs.io/en/latest/Basics/Quick-Start-UNet-HLAPI/#step-1a-setup-network-manager) correctly? If that's not run the HLAPI doesn't create any channels (not even the default ones) and so Dissonance can't send messages.

**Comment by cborg15** [comment]
Yes, everything appears to be setup correctly.

![image](https://user-images.githubusercontent.com/38264937/38587454-7e75515e-3cef-11e8-8166-02424db119e3.png)
![image](https://user-images.githubusercontent.com/38264937/38587548-de90e76a-3cef-11e8-9e79-be1583eb86d0.png)

**Comment by martindevans** [comment]
That does look correct. Could you send me (martin@placeholder-software.co.uk) an editor log of this happening so I can dig into the problem a little more. Thanks.

Before capturing the log go to `Window > Dissonance > Diagnostic settings` and change `Network` category to `Debug`. Make sure to change it back afterwards because that will spam you with a lot of messages!

**Comment by cborg15** [comment]
Did you not get the email?

**Comment by martindevans** [comment]
Hi cborg, Sorry about that, I haven't got the email. Could you try sending it again? Or attaching it to a reply on Github.

**Comment by cborg15** [comment]
Here it is.

**Comment by martindevans** [comment]
This log doesn't show the "ServerDisconnected due to error: Timeout" error happening. Was it cut off?

**Comment by cborg15** [comment]
I’m not sure. I could run it again and send a new copy to see if it will show up.

**Comment by martindevans** [comment]
The very last line was `(Filename: Assets/Plugins/Dissonance/Core/Log.cs Line` so it looks like it was cutoff. Probably truncated by your email host.

**Comment by cborg15** [comment]
Attached it as a zip file this time. Hopefully, it should be the whole thing.

**Comment by martindevans** [comment]
I'm really sorry but email attachments are ignored by Github. I think you'll have to attach it to a comment on the Github website (or try emailing it to me again, I'm not sure why it got lost last time).

**Comment by cborg15** [comment]
[Error Log.txt](https://github.com/Placeholder-Software/Dissonance/files/1907885/Error.Log.txt)

**Comment by martindevans** [comment]
I've got it, and this time it's 11610 lines long so I don't think it's been cut off! Sorry about all that.

**Comment by cborg15** [comment]
No worries. I didn't realize that my response in the email was going straight to this post.

**Comment by martindevans** [comment]
I've had a look through the log and really the only thing I can see in here is the disconnected event:

```
Log: connection {1} has been disconnected by timeout; address {::ffff:127.0.0.1:49244} time {3066612}, last rec time {3064604} rtt {12} timeout {2000}
ServerDisconnected due to error: Timeout
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.Networking.NetworkManager:OnServerDisconnect(NetworkConnection) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkManager.cs:1008)
UnityEngine.Networking.NetworkManager:OnServerDisconnectInternal(NetworkMessage) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkManager.cs:856)
UnityEngine.Networking.NetworkConnection:InvokeHandler(Int16, NetworkReader, Int32) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkConnection.cs:220)
UnityEngine.Networking.NetworkConnection:InvokeHandlerNoData(Int16) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkConnection.cs:202)
UnityEngine.Networking.NetworkServer:OnDisconnected(NetworkConnection) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkServer.cs:715)
UnityEngine.Networking.ServerSimpleWrapper:OnDisconnected(NetworkConnection) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkServer.cs:1861)
UnityEngine.Networking.NetworkServerSimple:HandleDisconnect(Int32, Byte) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkServerSimple.cs:364)
UnityEngine.Networking.NetworkServerSimple:Update() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkServerSimple.cs:253)
UnityEngine.Networking.NetworkServer:InternalUpdate() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkServer.cs:691)
UnityEngine.Networking.NetworkServer:Update() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkServer.cs:642)
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkIdentity.cs:1090)
```

However this is a UNet event (as you can see from the stacktrace). In fact this is what I'd expect to see if you kill a client - they disappear and the only reason the server knows they're gone is because they stop responding and time out (after 2 seconds, in this case).

If you run the same scene but without Dissonance in it do you encounter the same issue?

**Comment by martindevans** [comment]
Disable or remove the Dissonance related components in the scene. Is this the demo scene?

**Comment by cborg15** [comment]
Yes

**Comment by cborg15** [comment]
Still getting a timeout :/

**Comment by martindevans** [comment]
Well I must admit I'm glad it's not a Dissonance problem!

When you say the program crashes do you mean it actually stops running, or does it just display this error message and keep on running? I would expect it to display this kind of error when a client disappears (but obviously it shouldn't crash).

**Comment by cborg15** [comment]
My mistake. It doesn't crash. I just get the timeout error message in the log.
![image](https://user-images.githubusercontent.com/38264937/38745629-120de4ce-3f13-11e8-9e3a-0340cfae4655.png)

**Comment by martindevans** [comment]
Ah, in that case I think that's just how HLAPI handles disconnects (it seems to be a little inconsistent, sometimes it handles them gracefully and sometimes it just times them out). I'll close this issue now :)
