### ISSUE TITLE
HlapiPlayer OnStartAuthority question

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#9]
Hi,

1. Small thing, but the documentation seems to be out of date [here](https://dissonance.readthedocs.io/en/latest/Tutorials/Position-Tracking/), the `UNetPlayer` class doesn't exist and should be replaced with `HlapiPlayer`.

2. In `HlapiPlayer`, the function `OnStartAuthority` is called to add the player to the `DissonanceComms _trackedPlayers`. It is called only on the local player and not when a client is joining (the client doesn't have authority). Therefore the client is never added to the `_trackedPlayers` and the `PositionTrackingAvailable` is always false and the positional data are never used to update the position of the Playback object.

I changed the code in HlPlayer to make the positional data work:

```
        public override void OnStartClient()
        {
            if (hasAuthority == false) {

                base.OnStartClient();

                var comms = FindObjectOfType<DissonanceComms>();
                if (comms == null)
                    throw Log.UserError("cannot find DissonanceComms component in scene", "not placing a DissonanceComms component on a game object in the scene", "https://dissonance.readthedocs.io/en/latest/Basics/Getting%20Started/", "9A79FDCB-263E-4124-B54D-67EDA39C09A5");

                StartTracking();
            }
        }
```
Also, I removed `StartTracking()` in `OnStartAuthority`, I don't think it is useful to have it here since only remote client should be tracked?

Thanks

**Comment by martindevans** [comment]
I've looked into this and fixed both problems. The docs fix is already live. The position tracking fix will come with the next test version of Dissonance :)

**Comment by citron4000** [comment]
Hello,

I actually still have issues with this one. To reproduce the error you can just start a host and a client with the HlUnet demo scene in Dissonance 0.0.6. On the server position tracking works well. On the client however, the position of player of the host is never tracked (the Playback prefab stays at Vector3.zero).

Looking at the code, it seems tracking `OnStartAuthority` is the only place where `StartTracking` is called (through the `CmdSetPlayerName` Command that is called on the server **only**). `StartTracking` should also be called on the client side for all HlApiPlayer that connect.

I modified the code like this to make the position tracking work but it's probably not very clean:

```

        public override void OnStartAuthority()
        {
            base.OnStartAuthority();

            var comms = FindObjectOfType<DissonanceComms>();
            if (comms == null)
                throw Log.UserError("cannot find DissonanceComms component in scene", "not placing a DissonanceComms component on a game object in the scene", "https://dissonance.readthedocs.io/en/latest/Basics/Getting%20Started/", "9A79FDCB-263E-4124-B54D-67EDA39C09A5");

            SetPlayerName(comms.LocalPlayerName);
            comms.LocalPlayerNameChanged += SetPlayerName;
        }

        public override void OnStartClient()
        {
            base.OnStartClient();

            var comms = FindObjectOfType<DissonanceComms>();
            if (comms == null)
                throw Log.UserError("cannot find DissonanceComms component in scene", "not placing a DissonanceComms component on a game object in the scene", "https://dissonance.readthedocs.io/en/latest/Basics/Getting%20Started/", "9A79FDCB-263E-4124-B54D-67EDA39C09A5");

            Log.Debug("OnStartAuthority Name={0}", comms.LocalPlayerName);

            StartTracking();
        }
```

**Comment by martindevans** [comment]
Looks like this was a silly mistake - I was using the `[Command]` attribute to sync the call of `CmdSetPlayerName` on all clients but of course that calls it on the server, not all the other clients!

I'll fix this today and then probably get a release pushed out tomorrow which will include this fix.

**Comment by martindevans** [comment]
Oops, this got auto closed when Tom merged my PR to fix it!

**Comment by martindevans** [comment]
I've just pushed out 0.0.7 which includes the fix for this.

**Comment by citron4000** [comment]
Thanks! It's working now!
