### ISSUE TITLE
[iOS] Mute button, on the iPhone, stops turning off the sounds

### ISSUE THREAD

**Issue by alexander12356** [Placeholder-Software/Dissonance#95]
## Context
Hello, 
when you start a scene with Voice chat, the mute button, on the iPhone, stops turning off the sounds. Can we fix this somehow?

## Expected Behavior
Mute button on iPhone turning off all sounds and music

## Actual Behavior
Mute button on iPhone not turning off all sound and music

## Steps to Reproduce
1. Build integration project to iOS
2. In online scene turn off/on mute button

## Environment
- **Dissonance version used**: 6.2.0

- **Unity version**: 2017.4.2f2

- **Editor Operating System and version**: Mac OS 

- **Build Settings**: iOS release

- **Target device**: iPhone 6 plus, iOS: 10.02.

**Comment by martindevans** [comment]
Hi Alexander,

I think this needs to be reported to Unity - Dissonance just plays audio out as if it were any other sound effect so we're not doing anything special that would affect the mute button.

The only thing I can think is if perhaps using the mic disables the mute button?

**Comment by alexander12356** [comment]
Hi.
Thanks, it actually disables the mute button.

**Comment by martindevans** [comment]
Yep, what I'm wondering is do either of these (in a project without Unity) also disable the mute button:

    GetComponent<AudioSource>().PlayOneShot(clip);

i.e. Does playing audio with Unity disable the mute button?

Or perhaps:

    aud.clip = Microphone.Start("", true, 10, 44100);

i.e. Does activating the microphone in Unity disable the mute button?

Dissonance actually interacts with Unity itself in a very limited way (just recording and playback), so those twm seem like likely candidates.
