### ISSUE TITLE
[bug] DissonanceComms RemoteVoiceVolume only accepts zero

### ISSUE THREAD

**Issue by Zammstein** [Placeholder-Software/Dissonance#96]
## Context
DissonanceComms class, line 295

`if (value > 0) throw new ArgumentOutOfRangeException("value", "Value must be less than or equal to one");`

## Fix
`if (value > 1) throw new ArgumentOutOfRangeException("value", "Value must be less than or equal to one");`

This setter always throws an ArgumentOutOfRangeException if not passing zero

**Comment by martindevans** [comment]
Well spotted! I'll change that now.

**Comment by martindevans** [comment]
This has been fixed in Dissonance 6.2.3 which is now available on the asset store.
